#include "..\io\keyboard.h"
#include "..\features\script.h"
#include "..\debug\debuglog.h"
#include "..\io\controller.h"

extern bool featureControllerIgnoreInTrainer;

bool isUsingController()
{
	return !CONTROLS::_IS_INPUT_DISABLED(2);
}

// Resolves a bind name/slot to its eButton ID, or CONTROLLER_BUTTON_NONE if
// unbound or if the global controller-disable toggle is active - the single
// choke point every is_bind_* helper below funnels through.
static int resolve_bind_button(const std::string& bindName, int slot)
{
	if (featureControllerIgnoreInTrainer) return CONTROLLER_BUTTON_NONE;

	auto it = controller_binds.find(bindName);
	if (it == controller_binds.end()) return CONTROLLER_BUTTON_NONE;

	return slot == 2 ? it->second.secondary : it->second.primary;
}

bool is_bind_pressed(const std::string& bindName, int slot)
{
	int btn = resolve_bind_button(bindName, slot);
	return btn != CONTROLLER_BUTTON_NONE && CONTROLS::IS_CONTROL_PRESSED(2, btn);
}

bool is_bind_just_pressed(const std::string& bindName, int slot)
{
	int btn = resolve_bind_button(bindName, slot);
	return btn != CONTROLLER_BUTTON_NONE && CONTROLS::IS_CONTROL_JUST_PRESSED(2, btn);
}

bool is_bind_disabled_pressed(const std::string& bindName, int slot)
{
	int btn = resolve_bind_button(bindName, slot);
	return btn != CONTROLLER_BUTTON_NONE && CONTROLS::IS_DISABLED_CONTROL_PRESSED(2, btn);
}

bool is_bind_disabled_just_pressed(const std::string& bindName, int slot)
{
	int btn = resolve_bind_button(bindName, slot);
	return btn != CONTROLLER_BUTTON_NONE && CONTROLS::IS_DISABLED_CONTROL_JUST_PRESSED(2, btn);
}

bool is_bind_disabled_just_released(const std::string& bindName, int slot)
{
	int btn = resolve_bind_button(bindName, slot);
	return btn != CONTROLLER_BUTTON_NONE && CONTROLS::IS_DISABLED_CONTROL_JUST_RELEASED(2, btn);
}

void disableControls()
{
	if (!isUsingController())
	{
		UI::HIDE_HELP_TEXT_THIS_FRAME();
		CAM::SET_CINEMATIC_BUTTON_ACTIVE(1);
		CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_LOOK_BEHIND, TRUE);
		CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_NEXT_CAMERA, TRUE);
		CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_VEH_SELECT_NEXT_WEAPON, TRUE);
		CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_VEH_CIN_CAM, TRUE);
		CONTROLS::SET_INPUT_EXCLUSIVE(2, INPUT_FRONTEND_ACCEPT);
		CONTROLS::SET_INPUT_EXCLUSIVE(2, INPUT_FRONTEND_CANCEL);
		CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_HUD_SPECIAL, TRUE);
		CONTROLS::SET_INPUT_EXCLUSIVE(2, INPUT_FRONTEND_DOWN);
		CONTROLS::SET_INPUT_EXCLUSIVE(2, INPUT_FRONTEND_UP);
		CONTROLS::SET_INPUT_EXCLUSIVE(2, INPUT_FRONTEND_LEFT);
		CONTROLS::SET_INPUT_EXCLUSIVE(2, INPUT_FRONTEND_RIGHT);
		CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_FRONTEND_ACCEPT, TRUE);
		CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_FRONTEND_CANCEL, TRUE);
		CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_FRONTEND_LEFT, TRUE);
		CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_FRONTEND_RIGHT, TRUE);
		CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_FRONTEND_DOWN, TRUE);
		CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_FRONTEND_UP, TRUE);
		CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_FRONTEND_ACCEPT, TRUE);
		UI::HIDE_HUD_COMPONENT_THIS_FRAME(10);
		UI::HIDE_HUD_COMPONENT_THIS_FRAME(6);
		UI::HIDE_HUD_COMPONENT_THIS_FRAME(7);
		UI::HIDE_HUD_COMPONENT_THIS_FRAME(9);
		UI::HIDE_HUD_COMPONENT_THIS_FRAME(8);
		CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_SELECT_CHARACTER_FRANKLIN, TRUE);
		CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_SELECT_CHARACTER_MICHAEL, TRUE);
		CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_SELECT_CHARACTER_TREVOR, TRUE);
		CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_SELECT_CHARACTER_MULTIPLAYER, TRUE);
		CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_CHARACTER_WHEEL, TRUE);
		CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_CELLPHONE_CANCEL, TRUE);
		CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_CELLPHONE_SELECT, TRUE);
		CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_CELLPHONE_UP, TRUE);
		CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_CELLPHONE_DOWN, TRUE);
		return;
	}

	UI::HIDE_HELP_TEXT_THIS_FRAME();
	CAM::SET_CINEMATIC_BUTTON_ACTIVE(1);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_NEXT_CAMERA, TRUE);
	CONTROLS::SET_INPUT_EXCLUSIVE(2, INPUT_FRONTEND_X);
	CONTROLS::SET_INPUT_EXCLUSIVE(2, INPUT_FRONTEND_ACCEPT);
	CONTROLS::SET_INPUT_EXCLUSIVE(2, INPUT_FRONTEND_CANCEL);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_HUD_SPECIAL, TRUE);
	CONTROLS::SET_INPUT_EXCLUSIVE(2, INPUT_FRONTEND_DOWN);
	CONTROLS::SET_INPUT_EXCLUSIVE(2, INPUT_FRONTEND_UP);
	CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_FRONTEND_SELECT, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_FRONTEND_ACCEPT, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_FRONTEND_CANCEL, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_FRONTEND_LEFT, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_FRONTEND_RIGHT, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_FRONTEND_DOWN, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_FRONTEND_UP, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_FRONTEND_RDOWN, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_FRONTEND_ACCEPT, TRUE);
	UI::HIDE_HUD_COMPONENT_THIS_FRAME(10);
	UI::HIDE_HUD_COMPONENT_THIS_FRAME(6);
	UI::HIDE_HUD_COMPONENT_THIS_FRAME(7);
	UI::HIDE_HUD_COMPONENT_THIS_FRAME(9);
	UI::HIDE_HUD_COMPONENT_THIS_FRAME(8);
	CONTROLS::SET_INPUT_EXCLUSIVE(2, INPUT_FRONTEND_LEFT);
	CONTROLS::SET_INPUT_EXCLUSIVE(2, INPUT_FRONTEND_RIGHT);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_SELECT_WEAPON, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_SELECT_WEAPON_UNARMED, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_SELECT_WEAPON_MELEE, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_SELECT_WEAPON_HANDGUN, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_SELECT_WEAPON_SHOTGUN, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_SELECT_WEAPON_SMG, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_SELECT_WEAPON_AUTO_RIFLE, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_SELECT_WEAPON_SNIPER, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_SELECT_WEAPON_HEAVY, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_SELECT_WEAPON_SPECIAL, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_WEAPON_WHEEL_NEXT, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_WEAPON_WHEEL_PREV, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_WEAPON_SPECIAL, 1);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_WEAPON_SPECIAL_TWO, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_DIVE, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_MELEE_ATTACK_LIGHT, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_MELEE_ATTACK_HEAVY, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_MELEE_BLOCK, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_ARREST, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_VEH_HEADLIGHT, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_VEH_RADIO_WHEEL, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_CONTEXT, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_RELOAD, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_VEH_CIN_CAM, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_JUMP, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_VEH_SELECT_NEXT_WEAPON, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_VEH_FLY_SELECT_NEXT_WEAPON, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_SELECT_CHARACTER_FRANKLIN, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_SELECT_CHARACTER_MICHAEL, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_SELECT_CHARACTER_TREVOR, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_SELECT_CHARACTER_MULTIPLAYER, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_CHARACTER_WHEEL, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_CELLPHONE_CANCEL, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_CELLPHONE_SELECT, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_CELLPHONE_UP, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(2, INPUT_CELLPHONE_DOWN, TRUE);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_DETONATE, 1);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_SPRINT, 1);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_VEH_DUCK, 1);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_VEH_HEADLIGHT, 1);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_VEH_PUSHBIKE_SPRINT, 1);
	CONTROLS::DISABLE_CONTROL_ACTION(0, INPUT_VEH_PUSHBIKE_PEDAL, 1);
}