/*
Some of this code began its life as a part of GTA V SCRIPT HOOK SDK.
http://dev-c.com
(C) Alexander Blade 2015

It is now part of the Enhanced Native Trainer project.
https://github.com/gtav-ent/GTAV-EnhancedNativeTrainer
(C) Rob Pridham and fellow contributors 2015
*/

#pragma once

#include "..\..\inc\natives.h"
#include "..\..\inc\types.h"
#include "..\..\inc\enums.h"
#include "..\..\inc\main.h"
#include "..\ui_support\menu_functions.h"
#include "..\common\option_table.h"
#include <string>

const Option<std::string> SKINS_PLAYER_OPTIONS[] = {
	{ "Michael", "player_zero" },
	{ "Franklin", "player_one" },
	{ "Trevor", "player_two" },
	{ "MP Female", "mp_f_freemode_01" },
	{ "MP Male", "mp_m_freemode_01" }
};
const std::vector<std::string> SKINS_PLAYER_CAPTIONS = captionsOf(SKINS_PLAYER_OPTIONS);
const std::vector<std::string> SKINS_PLAYER_VALUES = valuesOf(SKINS_PLAYER_OPTIONS);

const Option<std::string> SKINS_ANIMAL_OPTIONS[] = {
	{ "Boar", "a_c_boar" },
	{ "Cat", "a_c_cat_01" },
	{ "Chimp", "a_c_chimp" },
	{ "Chimp 2", "A_C_Chimp_02" },
	{ "Chop", "a_c_chop" },
	{ "Cormorant", "a_c_cormorant" },
	{ "Cow", "a_c_cow" },
	{ "Coyote", "a_c_coyote" },
	{ "Crow", "a_c_crow" },
	{ "Deer", "a_c_deer" },
	{ "Dolphin", "a_c_dolphin" },
	{ "Fish", "a_c_fish" },
	{ "German Shepherd", "a_c_shepherd" },
	{ "Grey Whale", "a_c_whalegrey" },
	{ "Hammerhead Shark", "a_c_sharkhammer" },
	{ "Hawk", "a_c_chickenhawk" },
	{ "Hen", "a_c_hen" },
	{ "Humpback", "a_c_humpback" },
	{ "Husky", "a_c_husky" },
	{ "Killer Whale", "a_c_killerwhale" },
	{ "Mountain Lion", "a_c_mtlion" },
	{ "Panther", "a_c_Panther" },
	{ "Pig", "a_c_pig" },
	{ "Pigeon", "a_c_pigeon" },
	{ "Poodle", "a_c_poodle" },
	{ "Pug", "a_c_pug" },
	{ "Rabbit", "a_c_rabbit_01" },
	{ "Rabbit 2", "A_C_Rabbit_02" },
	{ "Rat", "a_c_rat" },
	{ "Retriever", "a_c_retriever" },
	{ "Rhesus", "a_c_rhesus" },
	{ "Rottweiler", "a_c_rottweiler" },
	{ "Seagull", "a_c_seagull" },
	{ "Stingray", "a_c_stingray" },
	{ "Tiger Shark", "a_c_sharktiger" },
	{ "Westy", "a_c_westy" }
};
const std::vector<std::string> SKINS_ANIMAL_CAPTIONS = captionsOf(SKINS_ANIMAL_OPTIONS);
const std::vector<std::string> SKINS_ANIMAL_VALUES = valuesOf(SKINS_ANIMAL_OPTIONS);

const Option<std::string> SKINS_GENERAL_OPTIONS[] = {
	{ "Abigail Mathers", "ig_abigail" },
	{ "Abner", "u_m_y_abner" },
	{ "African American Male", "a_m_m_afriamer_01" },
	{ "Agent", "ig_agent" },
	{ "Air Hostess", "s_f_y_airhostess_01" },
	{ "Air Worker Male", "s_m_y_airworker" },
	{ "Al Di Napoli Male", "u_m_m_aldinapoli" },
	{ "Alien", "s_m_m_movalien_01" },
	{ "Altruist Cult Mid-Age Male", "a_m_m_acult_01" },
	{ "Altruist Cult Old Male", "a_m_o_acult_01" },
	{ "Altruist Cult Old Male 2", "a_m_o_acult_02" },
	{ "Altruist Cult Young Male", "a_m_y_acult_01" },
	{ "Altruist Cult Young Male 2", "a_m_y_acult_02" },
	{ "Amanda De Santa", "ig_amandatownley" },
	{ "Ammu-Nation City Clerk", "s_m_y_ammucity_01" },
	{ "Ammu-Nation Rural Clerk", "s_m_m_ammucountry" },
	{ "Andreas Sanchez", "ig_andreas" },
	{ "Anita Mendoza", "csb_anita" },
	{ "Anton Beaudelaire", "csb_anton" },
	{ "Armenian Boss", "g_m_m_armboss_01" },
	{ "Armenian Goon", "g_m_m_armgoon_01" },
	{ "Armenian Goon 2", "g_m_y_armgoon_02" },
	{ "Armenian Lieutenant", "g_m_m_armlieut_01" },
	{ "Armoured Van Security", "s_m_m_armoured_01" },
	{ "Armoured Van Security 2", "s_m_m_armoured_02" },
	{ "Army Mechanic", "s_m_y_armymech_01" },
	{ "Ashley Butler", "ig_ashley" },
	{ "Autopsy Tech", "s_m_y_autopsy_01" },
	{ "Autoshop Worker", "s_m_m_autoshop_01" },
	{ "Autoshop Worker 2", "s_m_m_autoshop_02" },
	{ "Autoshop Worker 3", "s_m_m_autoshop_03" },
	{ "Azteca", "g_m_y_azteca_01" },
	{ "Baby D", "u_m_y_babyd" },
	{ "Ballas East Male", "g_m_y_ballaeast_01" },
	{ "Ballas Female", "g_f_y_ballas_01" },
	{ "Ballas OG", "ig_ballasog" },
	{ "Ballas Original Male", "g_m_y_ballaorig_01" },
	{ "Ballas South Male", "g_m_y_ballasout_01" },
	{ "Bank Manager", "ig_bankman" },
	{ "Barber Female", "s_f_m_fembarber" },
	{ "Barman", "s_m_y_barman_01" },
	{ "Barry", "ig_barry" },
	{ "Bartender", "s_f_y_bartender_01" },
	{ "Bartender (Rural)", "s_m_m_cntrybar_01" },
	{ "Baywatch Female", "s_f_y_baywatch_01" },
	{ "Baywatch Male", "s_m_y_baywatch_01" },
	{ "Beach Female", "a_f_m_beach_01" },
	{ "Beach Male", "a_m_m_beach_01" },
	{ "Beach Male 2", "a_m_m_beach_02" },
	{ "Beach Muscle Male", "a_m_y_musclbeac_01" },
	{ "Beach Muscle Male 2", "a_m_y_musclbeac_02" },
	{ "Beach Old Male", "a_m_o_beach_01" },
	{ "Beach Tramp Female", "a_f_m_trampbeac_01" },
	{ "Beach Tramp Male", "a_m_m_trampbeac_01" },
	{ "Beach Young Female", "a_f_y_beach_01" },
	{ "Beach Young Male", "a_m_y_beach_01" },
	{ "Beach Young Male 2", "a_m_y_beach_02" },
	{ "Beach Young Male 3", "a_m_y_beach_03" },
	{ "Best Man", "ig_bestmen" },
	{ "Beverly Felton", "ig_beverly" },
	{ "Beverly Hills Female", "a_f_m_bevhills_01" },
	{ "Beverly Hills Female 2", "a_f_m_bevhills_02" },
	{ "Beverly Hills Male", "a_m_m_bevhills_01" },
	{ "Beverly Hills Male 2", "a_m_m_bevhills_02" },
	{ "Beverly Hills Young Female", "a_f_y_bevhills_01" },
	{ "Beverly Hills Young Female 2", "a_f_y_bevhills_02" },
	{ "Beverly Hills Young Female 3", "a_f_y_bevhills_03" },
	{ "Beverly Hills Young Female 4", "a_f_y_bevhills_04" },
	{ "Beverly Hills Young Male", "a_m_y_bevhills_01" },
	{ "Beverly Hills Young Male 2", "a_m_y_bevhills_02" },
	{ "Bigfoot", "ig_orleans" },
	{ "Bike Hire Guy", "u_m_m_bikehire_01" },
	{ "Biker Chic Female", "u_f_y_bikerchic" },
	{ "Black Ops Soldier", "s_m_y_blackops_01" },
	{ "Black Ops Soldier 2", "s_m_y_blackops_02" },
	{ "Black Street Male", "a_m_y_stbla_01" },
	{ "Black Street Male 2", "a_m_y_stbla_02" },
	{ "Bodybuilder Female", "a_f_m_bodybuild_01" },
	{ "Bouncer", "s_m_m_bouncer_01" },
	{ "Brad", "ig_brad" },
	{ "Brad's Cadaver", "cs_bradcadaver" },
	{ "Breakdancer Male", "a_m_y_breakdance_01" },
	{ "Bride", "ig_bride" },
	{ "Burger Drug Worker", "u_m_y_burgerdrug_01" },
	{ "Busboy", "s_m_y_busboy_01" },
	{ "Business Casual", "a_m_y_busicas_01" },
	{ "Business Female 2", "a_f_m_business_02" },
	{ "Business Male", "a_m_m_business_01" },
	{ "Business Young Female", "a_f_y_business_01" },
	{ "Business Young Female 2", "a_f_y_business_02" },
	{ "Business Young Female 3", "a_f_y_business_03" },
	{ "Business Young Female 4", "a_f_y_business_04" },
	{ "Business Young Male", "a_m_y_business_01" },
	{ "Business Young Male 2", "a_m_y_business_02" },
	{ "Business Young Male 3", "a_m_y_business_03" },
	{ "Busker", "s_m_o_busker_01" },
	{ "Car 3 Guy 1", "ig_car3guy1" },
	{ "Car 3 Guy 2", "ig_car3guy2" },
	{ "Car Buyer", "cs_carbuyer" },
	{ "Casey", "ig_casey" },
	{ "Chef aka Head Cook", "s_m_y_chef_01" },
	{ "Chef", "ig_chef2" },
	{ "Chemical Plant Security", "s_m_m_chemsec_01" },
	{ "Chemical Plant Worker", "g_m_m_chemwork_01" },
	{ "Chinese Boss", "g_m_m_chiboss_01" },
	{ "Chinese Goon", "g_m_m_chigoon_01" },
	{ "Chinese Goon 2", "csb_chin_goon" },
	{ "Chinese Goon 3", "g_m_m_chigoon_02" },
	{ "Chinese Goon Older", "g_m_m_chicold_01" },
	{ "Chip", "u_m_y_chip" },
	{ "Claude Speed", "mp_m_claude_01" },
	{ "Clay Jackson (The Pain Giver)", "ig_claypain" },
	{ "Clay Simons (The Lost)", "ig_clay" },
	{ "Cletus", "ig_cletus" },
	{ "Clown", "s_m_y_clown_01" },
	{ "Construction Worker", "s_m_y_construct_01" },
	{ "Construction Worker 2", "s_m_y_construct_02" },
	{ "Cop", "csb_cop" },
	{ "Cop Female", "s_f_y_cop_01" },
	{ "Cop Male", "s_m_y_cop_01" },
	{ "Corpse Female", "u_f_m_corpse_01" },
	{ "Corpse Young Female", "u_f_y_corpse_01" },
	{ "Corpse Young Female 2", "u_f_y_corpse_02" },
	{ "Crew Member", "s_m_m_ccrew_01" },
	{ "Cris Formage", "ig_chrisformage" },
	{ "Customer", "csb_customer" },
	{ "Cyclist Male", "a_m_y_cyclist_01" },
	{ "Cyclist Male 2", "u_m_y_cyclist_01" },
	{ "Dale", "ig_dale" },
	{ "Dave Norton", "ig_davenorton" },
	{ "Dead Hooker", "mp_f_deadhooker" },
	{ "Dealer", "s_m_y_dealer_01" },
	{ "Debra", "cs_debra" },
	{ "Denise", "ig_denise" },
	{ "Denise's Friend", "csb_denise_friend" },
	{ "Devin Weston", "ig_devin" },
	{ "Devin's Security", "s_m_y_devinsec_01" },
	{ "DOA Man", "u_m_m_doa_01" },
	{ "Dock Worker", "s_m_m_dockwork_01" },
	{ "Dock Worker 2", "s_m_y_dockwork_01" },
	{ "Doctor", "s_m_m_doctor_01" },
	{ "Dom Beasley", "ig_dom" },
	{ "Doorman", "s_m_y_doorman_01" },
	{ "Downhill Cyclist", "a_m_y_dhill_01" },
	{ "Downtown Female", "a_f_m_downtown_01" },
	{ "Downtown Male", "a_m_y_downtown_01" },
	{ "Dr. Friedlander", "ig_drfriedlander" },
	{ "Dressy Female", "a_f_y_scdressy_01" },
	{ "DW Airport Worker", "s_m_y_dwservice_01" },
	{ "East SA Female", "a_f_m_eastsa_01" },
	{ "East SA Female 2", "a_f_m_eastsa_02" },
	{ "East SA Male", "a_m_m_eastsa_01" },
	{ "East SA Male 2", "a_m_m_eastsa_02" },
	{ "East SA Young Female", "a_f_y_eastsa_01" },
	{ "East SA Young Female 2", "a_f_y_eastsa_02" },
	{ "East SA Young Female 3", "a_f_y_eastsa_03" },
	{ "East SA Young Male", "a_m_y_eastsa_01" },
	{ "East SA Young Male 2", "a_m_y_eastsa_02" },
	{ "Ed Toh", "u_m_m_edtoh" },
	{ "Epsilon Female", "a_f_y_epsilon_01" },
	{ "Epsilon Male", "a_m_y_epsilon_01" },
	{ "Epsilon Male 2", "a_m_y_epsilon_02" },
	{ "Epsilon Tom", "ig_tomepsilon" },
	{ "Ex-Army Male", "mp_m_exarmy_01" },
	{ "Ex-Mil Bum", "u_m_y_militarybum" },
	{ "Fabien", "ig_fabien" },
	{ "Factory Worker Female", "s_f_y_factory_01" },
	{ "Factory Worker Male", "s_m_y_factory_01" },
	{ "Families CA Male", "g_m_y_famca_01" },
	{ "Families DD Male", "mp_m_famdd_01" },
	{ "Families DNF Male", "g_m_y_famdnf_01" },
	{ "Families Female", "g_f_y_families_01" },
	{ "Families FOR Male", "g_m_y_famfor_01" },
	{ "Families Gang Member", "csb_ramp_gang" },
	{ "Farmer", "a_m_m_farmer_01" },
	{ "Fat Black Female", "a_f_m_fatbla_01" },
	{ "Fat Cult Female", "a_f_m_fatcult_01" },
	{ "Fat Latino Male", "a_m_m_fatlatin_01" },
	{ "Fat White Female", "a_f_m_fatwhite_01" },
	{ "Female Agent", "a_f_y_femaleagent" },
	{ "Ferdinand Kerimov (Mr. K)", "ig_mrk" },
	{ "FIB Architect", "u_m_m_fibarchitect" },
	{ "FIB Mugger", "u_m_y_fibmugger_01" },
	{ "FIB Office Worker", "s_m_m_fiboffice_01" },
	{ "FIB Office Worker 2", "s_m_m_fiboffice_02" },
	{ "FIB Security", "s_m_m_fibsec_01" },
	{ "FIB Suit", "ig_fbisuit_01" },
	{ "Financial Guru", "u_m_o_finguru_01" },
	{ "Fireman Male", "s_m_y_fireman_01" },
	{ "Fitness Female", "a_f_y_fitness_01" },
	{ "Fitness Female 2", "a_f_y_fitness_02" },
	{ "Floyd Hebert", "ig_floyd" },
	{ "FOS Rep", "csb_fos_rep" },
	{ "Gaffer", "s_m_m_gaffer_01" },
	{ "Garbage Worker", "s_m_y_garbage" },
	{ "Gardener", "s_m_m_gardener_01" },
	{ "Gay Male", "a_m_y_gay_01" },
	{ "Gay Male 2", "a_m_y_gay_02" },
	{ "General Fat Male", "a_m_m_genfat_01" },
	{ "General Fat Male 2", "a_m_m_genfat_02" },
	{ "General Hot Young Female", "a_f_y_genhot_01" },
	{ "General Street Old Female", "a_f_o_genstreet_01" },
	{ "General Street Old Male", "a_m_o_genstreet_01" },
	{ "General Street Young Male", "a_m_y_genstreet_01" },
	{ "General Street Young Male 2", "a_m_y_genstreet_02" },
	{ "Glenstank Male", "u_m_m_glenstank_01" },
	{ "Golfer Male", "a_m_m_golfer_01" },
	{ "Golfer Young Female", "a_f_y_golfer_01" },
	{ "Golfer Young Male", "a_m_y_golfer_01" },
	{ "Griff", "u_m_m_griff_01" },
	{ "Grip", "s_m_y_grip_01" },
	{ "Groom", "ig_groom" },
	{ "Grove Street Dealer", "csb_grove_str_dlr" },
	{ "Guadalope", "cs_guadalope" },
	{ "Guido", "u_m_y_guido_01" },
	{ "Gun Vendor", "u_m_y_gunvend_01" },
	{ "Gurk", "cs_gurk" },
	{ "Hairdresser Male", "s_m_m_hairdress_01" },
	{ "Hao", "ig_hao" },
	{ "Hasidic Jew Male", "a_m_m_hasjew_01" },
	{ "Hasidic Jew Young Male", "a_m_y_hasjew_01" },
	{ "Hick", "ig_ramp_hic" },
	{ "High Security", "s_m_m_highsec_01" },
	{ "High Security 2", "s_m_m_highsec_02" },
	{ "Highway Cop", "s_m_y_hwaycop_01" },
	{ "Hiker Female", "a_f_y_hiker_01" },
	{ "Hiker Male", "a_m_y_hiker_01" },
	{ "Hillbilly Male", "a_m_m_hillbilly_01" },
	{ "Hillbilly Male 2", "a_m_m_hillbilly_02" },
	{ "Hippie Female", "a_f_y_hippie_01" },
	{ "Hippie Male", "u_m_y_hippie_01" },
	{ "Hippie Male 2", "a_m_y_hippy_01" },
	{ "Hipster", "ig_ramp_hipster" },
	{ "Hipster Female", "a_f_y_hipster_01" },
	{ "Hipster Female 2", "a_f_y_hipster_02" },
	{ "Hipster Female 3", "a_f_y_hipster_03" },
	{ "Hipster Female 4", "a_f_y_hipster_04" },
	{ "Hipster Male", "a_m_y_hipster_01" },
	{ "Hipster Male 2", "a_m_y_hipster_02" },
	{ "Hipster Male 3", "a_m_y_hipster_03" },
	{ "Hooker", "s_f_y_hooker_01" },
	{ "Hooker 2", "s_f_y_hooker_02" },
	{ "Hooker 3", "s_f_y_hooker_03" },
	{ "Hospital Scrubs Female", "s_f_y_scrubs_01" },
	{ "Hot Posh Female", "u_f_y_hotposh_01" },
	{ "Hugh Harrison", "csb_hugh" },
	{ "Hunter", "ig_hunter" },
	{ "IAA Security", "s_m_m_ciasec_01" },
	{ "Impotent Rage", "u_m_y_imporage" },
	{ "Imran Shinowa", "csb_imran" },
	{ "Indian Male", "a_m_m_indian_01" },
	{ "Indian Old Female", "a_f_o_indian_01" },
	{ "Indian Young Female", "a_f_y_indian_01" },
	{ "Indian Young Male", "a_m_y_indian_01" },
	{ "Jane", "u_f_y_comjane" },
	{ "Janet", "ig_janet" },
	{ "Janitor", "s_m_m_janitor" },
	{ "Jay Norris", "ig_jay_norris" },
	{ "Jesco White (Tapdancing Hillbilly)", "u_m_o_taphillbilly" },
	{ "Jesus", "u_m_m_jesus_01" },
	{ "Jetskier", "a_m_y_jetski_01" },
	{ "Jewel Heist Driver", "hc_driver" },
	{ "Jewel Heist Hacker", "hc_hacker" },
	{ "Jewel Thief", "u_m_m_jewelthief" },
	{ "Jeweller Assistant", "u_f_y_jewelass_01" },
	{ "Jeweller Assistant", "ig_jewelass" },
	{ "Jeweller Security", "u_m_m_jewelsec_01" },
	{ "Jimmy Boston", "ig_jimmyboston" },
	{ "Jimmy De Santa", "ig_jimmydisanto" },
	{ "Jogger Female", "a_f_y_runner_01" },
	{ "Jogger Male", "a_m_y_runner_01" },
	{ "Jogger Male 2", "a_m_y_runner_02" },
	{ "John Marston", "mp_m_marston_01" },
	{ "Johnny Klebitz", "ig_johnnyklebitz" },
	{ "Josef", "ig_josef" },
	{ "Josh", "ig_josh" },
	{ "Juggalo Female", "a_f_y_juggalo_01" },
	{ "Juggalo Male", "a_m_y_juggalo_01" },
	{ "Justin", "u_m_y_justin" },
	{ "Karen Daniels", "ig_karen_daniels" },
	{ "Kerry McIntosh", "ig_kerrymcintosh" },
	{ "Kifflom Guy", "u_m_y_baygor" },
	{ "Korean Boss", "g_m_m_korboss_01" },
	{ "Korean Female", "a_f_m_ktown_01" },
	{ "Korean Female 2", "a_f_m_ktown_02" },
	{ "Korean Lieutenant", "g_m_y_korlieut_01" },
	{ "Korean Male", "a_m_m_ktown_01" },
	{ "Korean Old Female", "a_f_o_ktown_01" },
	{ "Korean Old Male", "a_m_o_ktown_01" },
	{ "Korean Young Male", "g_m_y_korean_01" },
	{ "Korean Young Male 2", "a_m_y_ktown_01" },
	{ "Korean Young Male 3", "g_m_y_korean_02" },
	{ "Korean Young Male 4", "a_m_y_ktown_02" },
	{ "Lamar Davis", "ig_lamardavis" },
	{ "Latino Handyman Male", "s_m_m_lathandy_01" },
	{ "Latino Street Male 2", "a_m_m_stlat_02" },
	{ "Latino Street Young Male", "a_m_y_stlat_01" },
	{ "Latino Young Male", "a_m_y_latino_01" },
	{ "Lazlow", "ig_lazlow" },
	{ "Lester Crest", "ig_lestercrest" },
	{ "Life Invader Male 1", "ig_lifeinvad_02" },
	{ "Life Invader Male 2", "s_m_m_lifeinvad_01" },
	{ "Line Cook", "s_m_m_linecook" },
	{ "Love Fist Willy", "u_m_m_willyfist" },
	{ "LS Metro Worker Male", "s_m_m_lsmetro_01" },
	{ "Magenta", "ig_magenta" },
	{ "Maid", "s_f_m_maid_01" },
	{ "Malibu Male", "a_m_m_malibu_01" },
	{ "Mani", "u_m_y_mani" },
	{ "Manuel", "ig_manuel" },
	{ "Mariachi", "s_m_m_mariachi_01" },
	{ "Marine", "csb_ramp_marine" },
	{ "Marine 2", "s_m_m_marine_01" },
	{ "Marine 3", "s_m_m_marine_02" },
	{ "Marine Young", "s_m_y_marine_01" },
	{ "Marine Young 2", "s_m_y_marine_02" },
	{ "Mark Fostenburg", "u_m_m_markfost" },
	{ "Marnie Allen", "ig_marnie" },
	{ "Martin Madrazo", "cs_martinmadrazo" },
	{ "Mary-Ann Quinn", "ig_maryann" },
	{ "Maude", "ig_maude" },
	{ "Mechanic", "s_m_y_xmech_01" },
	{ "Mechanic 2", "s_m_y_xmech_02" },
	{ "Merryweather Merc", "csb_mweather" },
	{ "Meth Addict", "a_m_y_methhead_01" },
	{ "Mexican", "ig_ramp_mex" },
	{ "Mexican Boss", "g_m_m_mexboss_01" },
	{ "Mexican Boss 2", "g_m_m_mexboss_02" },
	{ "Mexican Gang Member", "g_m_y_mexgang_01" },
	{ "Mexican Goon", "g_m_y_mexgoon_01" },
	{ "Mexican Goon 2", "g_m_y_mexgoon_02" },
	{ "Mexican Goon 3", "g_m_y_mexgoon_03" },
	{ "Mexican Labourer", "a_m_m_mexlabor_01" },
	{ "Mexican Rural", "a_m_m_mexcntry_01" },
	{ "Mexican Thug", "a_m_y_mexthug_01" },
	{ "Migrant Female", "s_f_y_migrant_01" },
	{ "Migrant Male", "s_m_m_migrant_01" },
	{ "Milton McIlroy", "ig_milton" },
	{ "Mime Artist", "s_m_y_mime" },
	{ "Minuteman Joe", "ig_joeminuteman" },
	{ "Miranda", "u_f_m_miranda" },
	{ "Mistress", "u_f_y_mistress" },
	{ "Misty", "mp_f_misty_01" },
	{ "Molly", "ig_molly" },
	{ "Money Man", "ig_money" },
	{ "Motocross Biker", "a_m_y_motox_01" },
	{ "Motocross Biker 2", "a_m_y_motox_02" },
	{ "Movie Astronaut", "s_m_m_movspace_01" },
	{ "Movie Director", "u_m_m_filmdirector" },
	{ "Movie Premiere Female", "s_f_y_movprem_01" },
	{ "Movie Premiere Male", "s_m_m_movprem_01" },
	{ "Movie Star Female", "u_f_o_moviestar" },
	{ "Mrs. Phillips", "ig_mrsphillips" },
	{ "Mrs. Thornhill", "ig_mrs_thornhill" },
	{ "Natalia", "ig_natalia" },
	{ "Nervous Ron", "ig_nervousron" },
	{ "Nigel", "ig_nigel" },
	{ "Niko Bellic", "mp_m_niko_01" },
	{ "OG Boss", "a_m_m_og_boss_01" },
	{ "Old Man 1", "ig_old_man1a" },
	{ "Old Man 2", "ig_old_man2" },
	{ "Omega", "ig_omega" },
	{ "O'Neil Brother", "ig_oneil" },
	{ "Ortega", "ig_ortega" },
	{ "Oscar", "csb_oscar" },
	{ "Paige Harris", "ig_paige" },
	{ "Paparazzi Male", "a_m_m_paparazzi_01" },
	{ "Paparazzi Young Male", "u_m_y_paparazzi" },
	{ "Paramedic", "s_m_m_paramedic_01" },
	{ "Party Target", "u_m_m_partytarget" },
	{ "Partygoer", "u_m_y_party_01" },
	{ "Patricia", "ig_patricia" },
	{ "Patrick McReary & Others", "hc_gunman" },
	{ "Pest Control", "s_m_y_pestcont_01" },
	{ "Peter Dreyfuss", "ig_dreyfuss" },
	{ "Pilot", "s_m_m_pilot_01" },
	{ "Pilot 2", "s_m_y_pilot_01" },
	{ "Pilot 3", "s_m_m_pilot_02" },
	{ "Pogo The Monkey", "u_m_y_pogo_01" },
	{ "Polynesian", "a_m_m_polynesian_01" },
	{ "Polynesian Goon", "g_m_y_pologoon_01" },
	{ "Polynesian Goon 2", "g_m_y_pologoon_02" },
	{ "Polynesian Young", "a_m_y_polynesian_01" },
	{ "Poppy Mitchell", "u_f_y_poppymich" },
	{ "Porn Dude", "csb_porndudes" },
	{ "Postal Worker Male", "s_m_m_postal_01" },
	{ "Postal Worker Male 2", "s_m_m_postal_02" },
	{ "Priest", "ig_priest" },
	{ "Princess", "u_f_y_princess" },
	{ "Prison Guard", "s_m_m_prisguard_01" },
	{ "Prisoner", "s_m_y_prisoner_01" },
	{ "Prisoner 2", "u_m_y_prisoner_01" },
	{ "Prisoner (Muscular)", "s_m_y_prismuscl_01" },
	{ "Prologue Driver", "u_m_y_proldriver_01" },
	{ "Prologue Host Female", "a_f_m_prolhost_01" },
	{ "Prologue Host Male", "a_m_m_prolhost_01" },
	{ "Prologue Host Old Female", "u_f_o_prolhost_01" },
	{ "Prologue Mourner Female", "u_f_m_promourn_01" },
	{ "Prologue Mourner Male", "u_m_m_promourn_01" },
	{ "Prologue Security", "csb_prolsec" },
	{ "Prologue Security (Shot)", "u_m_m_prolsec_01" },
	{ "Prologue Security 2", "ig_prolsec_02" },
	{ "Pros", "mp_g_m_pros_01" },
	{ "Ranger Female", "s_f_y_ranger_01" },
	{ "Ranger Male", "s_m_y_ranger_01" },
	{ "Reporter", "csb_reporter" },
	{ "Republican Space Ranger", "u_m_y_rsranger_01" },
	{ "Richard Lukens", "ig_lifeinvad_01" },
	{ "Rival Paparazzo", "u_m_m_rivalpap" },
	{ "Road Cyclist", "a_m_y_roadcyc_01" },
	{ "Robber", "s_m_y_robber_01" },
	{ "Rocco Pelosi", "ig_roccopelosi" },
	{ "Rural Meth Addict Female", "a_f_y_rurmeth_01" },
	{ "Rural Meth Addict Male", "a_m_m_rurmeth_01" },
	{ "Russian Drunk", "ig_russiandrunk" },
	{ "Sales Assistant (High-End)", "s_f_m_shop_high" },
	{ "Sales Assistant (Low-End)", "s_f_y_shop_low" },
	{ "Sales Assistant (Mask Stall)", "s_m_y_shop_mask" },
	{ "Sales Assistant (Mid-Price)", "s_f_y_shop_mid" },
	{ "Salton Female", "a_f_m_salton_01" },
	{ "Salton Male", "a_m_m_salton_01" },
	{ "Salton Male 2", "a_m_m_salton_02" },
	{ "Salton Male 3", "a_m_m_salton_03" },
	{ "Salton Male 4", "a_m_m_salton_04" },
	{ "Salton Old Female", "a_f_o_salton_01" },
	{ "Salton Old Male", "a_m_o_salton_01" },
	{ "Salton Young Male", "a_m_y_salton_01" },
	{ "Salvadoran Boss", "g_m_y_salvaboss_01" },
	{ "Salvadoran Goon", "g_m_y_salvagoon_01" },
	{ "Salvadoran Goon 2", "g_m_y_salvagoon_02" },
	{ "Salvadoran Goon 3", "g_m_y_salvagoon_03" },
	{ "Scientist", "s_m_m_scientist_01" },
	{ "Screenwriter", "ig_screen_writer" },
	{ "Security Guard", "s_m_m_security_01" },
	{ "Sheriff Female", "s_f_y_sheriff_01" },
	{ "Sheriff Male", "s_m_y_sheriff_01" },
	{ "Shopkeeper", "mp_m_shopkeep_01" },
	{ "Simeon Yetarian", "ig_siemonyetarian" },
	{ "Skater Female", "a_f_y_skater_01" },
	{ "Skater Male", "a_m_m_skater_01" },
	{ "Skater Young Male", "a_m_y_skater_01" },
	{ "Skater Young Male 2", "a_m_y_skater_02" },
	{ "Skid Row Female", "a_f_m_skidrow_01" },
	{ "Skid Row Male", "a_m_m_skidrow_01" },
	{ "Snow Cop Male", "s_m_m_snowcop_01" },
	{ "Solomon Richards", "ig_solomon" },
	{ "South Central Female", "a_f_m_soucent_01" },
	{ "South Central Female 2", "a_f_m_soucent_02" },
	{ "South Central Latino Male", "a_m_m_socenlat_01" },
	{ "South Central Male", "a_m_m_soucent_01" },
	{ "South Central Male 2", "a_m_m_soucent_02" },
	{ "South Central Male 3", "a_m_m_soucent_03" },
	{ "South Central Male 4", "a_m_m_soucent_04" },
	{ "South Central MC Female", "a_f_m_soucentmc_01" },
	{ "South Central Old Female", "a_f_o_soucent_01" },
	{ "South Central Old Female 2", "a_f_o_soucent_02" },
	{ "South Central Old Male", "a_m_o_soucent_01" },
	{ "South Central Old Male 2", "a_m_o_soucent_02" },
	{ "South Central Old Male 3", "a_m_o_soucent_03" },
	{ "South Central Young Female", "a_f_y_soucent_01" },
	{ "South Central Young Female 2", "a_f_y_soucent_02" },
	{ "South Central Young Female 3", "a_f_y_soucent_03" },
	{ "South Central Young Male", "a_m_y_soucent_01" },
	{ "South Central Young Male 2", "a_m_y_soucent_02" },
	{ "South Central Young Male 3", "a_m_y_soucent_03" },
	{ "South Central Young Male 4", "a_m_y_soucent_04" },
	{ "Sports Biker", "u_m_y_sbike" },
	{ "Spy Actor", "u_m_m_spyactor" },
	{ "Spy Actress", "u_f_y_spyactress" },
	{ "Stag Party Groom", "u_m_y_staggrm_01" },
	{ "Steve Haines", "ig_stevehains" },
	{ "Street Performer", "s_m_m_strperf_01" },
	{ "Street Preacher", "s_m_m_strpreach_01" },
	{ "Street Punk", "g_m_y_strpunk_01" },
	{ "Street Punk 2", "g_m_y_strpunk_02" },
	{ "Street Vendor", "s_m_m_strvend_01" },
	{ "Street Vendor Young", "s_m_y_strvend_01" },
	{ "Stretch", "ig_stretch" },
	{ "Stripper", "s_f_y_stripper_01" },
	{ "Stripper 2", "s_f_y_stripper_02" },
	{ "Sunbather Male", "a_m_y_sunbathe_01" },
	{ "Surfer", "a_m_y_surfer_01" },
	{ "SWAT", "s_m_y_swat_01" },
	{ "Sweatshop Worker", "s_f_m_sweatshop_01" },
	{ "Sweatshop Worker Young", "s_f_y_sweatshop_01" },
	{ "Taliana Martinez", "ig_talina" },
	{ "Tanisha", "ig_tanisha" },
	{ "Tao Cheng", "ig_taocheng" },
	{ "Tao's Translator", "ig_taostranslator" },
	{ "Tattoo Artist", "u_m_y_tattoo_01" },
	{ "Tennis Coach", "ig_tenniscoach" },
	{ "Tennis Player Female", "a_f_y_tennis_01" },
	{ "Tennis Player Male", "a_m_m_tennis_01" },
	{ "Terry", "ig_terry" },
	{ "The Lost MC Female", "g_f_y_lost_01" },
	{ "The Lost MC Male", "g_m_y_lost_01" },
	{ "The Lost MC Male 2", "g_m_y_lost_02" },
	{ "The Lost MC Male 3", "g_m_y_lost_03" },
	{ "Tom", "cs_tom" },
	{ "Tonya", "ig_tonya" },
	{ "Topless", "a_f_y_topless_01" },
	{ "Tourist Female", "a_f_m_tourist_01" },
	{ "Tourist Male", "a_m_m_tourist_01" },
	{ "Tourist Young Female", "a_f_y_tourist_01" },
	{ "Tourist Young Female 2", "a_f_y_tourist_02" },
	{ "Tracey De Santa", "ig_tracydisanto" },
	{ "Traffic Warden", "ig_trafficwarden" },
	{ "Tramp Female", "a_f_m_tramp_01" },
	{ "Tramp Male", "a_m_m_tramp_01" },
	{ "Tramp Old Male", "u_m_o_tramp_01" },
	{ "Tramp Old Male 2", "a_m_o_tramp_01" },
	{ "Transport Worker Male", "s_m_m_gentransport" },
	{ "Transvestite Male", "a_m_m_tranvest_01" },
	{ "Transvestite Male 2", "a_m_m_tranvest_02" },
	{ "Trucker Male", "s_m_m_trucker_01" },
	{ "Tyler Dixon", "ig_tylerdix" },
	{ "United Paper Man", "ig_paper" },
	{ "UPS Driver", "s_m_m_ups_01" },
	{ "UPS Driver 2", "s_m_m_ups_02" },
	{ "US Coastguard", "s_m_y_uscg_01" },
	{ "Vagos Female", "g_f_y_vagos_01" },
	{ "Valet", "s_m_y_valet_01" },
	{ "Vespucci Beach Male", "a_m_y_beachvesp_01" },
	{ "Vespucci Beach Male 2", "a_m_y_beachvesp_02" },
	{ "Vinewood Douche", "a_m_y_vindouche_01" },
	{ "Vinewood Female", "a_f_y_vinewood_01" },
	{ "Vinewood Female 2", "a_f_y_vinewood_02" },
	{ "Vinewood Female 3", "a_f_y_vinewood_03" },
	{ "Vinewood Female 4", "a_f_y_vinewood_04" },
	{ "Vinewood Male", "a_m_y_vinewood_01" },
	{ "Vinewood Male 2", "a_m_y_vinewood_02" },
	{ "Vinewood Male 3", "a_m_y_vinewood_03" },
	{ "Vinewood Male 4", "a_m_y_vinewood_04" },
	{ "Wade", "ig_wade" },
	{ "Waiter", "s_m_y_waiter_01" },
	{ "Wei Cheng", "ig_chengsr" },
	{ "White Street Male", "a_m_y_stwhi_01" },
	{ "White Street Male 2", "a_m_y_stwhi_02" },
	{ "Window Cleaner", "s_m_y_winclean_01" },
	{ "Yoga Female", "a_f_y_yoga_01" },
	{ "Yoga Male", "a_m_y_yoga_01" },
	{ "Zimbor", "ig_zimbor" },
	{ "Zombie1", "u_m_y_zombie_01" },
	{ "Zombie2", "G_M_M_Zombie_01" },
	{ "Zombie3", "G_M_M_Zombie_02" }
};
const std::vector<std::string> SKINS_GENERAL_CAPTIONS = captionsOf(SKINS_GENERAL_OPTIONS);
const std::vector<std::string> SKINS_GENERAL_VALUES = valuesOf(SKINS_GENERAL_OPTIONS);

const Option<std::string> SKINS_ONLINE_OPTIONS[] = {
	{ "&Me", "IG_IslDJ_01" },
	{ "Acid Lab Cook", "IG_AcidLabCook" },
	{ "Adam Port", "IG_IslDJ_02" },
	{ "Agent 14", "ig_mp_agent14" },
	{ "Avery", "csb_avery" },
	{ "Avi Schwartzman", "ig_avischwartzman_02" },
	{ "Avon Hertz", "IG_Avon" },
	{ "Avon's Goon", "mp_m_avongoon" },
	{ "Bail Office", "S_M_M_BailOffice_01" },
	{ "Ballas Leader", "IG_Ballas_Leader" },
	{ "Bank Robber", "A_M_M_BankRobber_01" },
	{ "Benny", "ig_benny" },
	{ "Billionaire", "IG_Billionaire" },
	{ "Bogdan", "csb_bogdan" },
	{ "Bogdan's Goon", "mp_m_bogdangoon" },
	{ "Bounty Target 1", "IG_BountyTarget_01" },
	{ "Bounty Target 2", "IG_BountyTarget_02" },
	{ "Bounty Target 3", "IG_BountyTarget_03" },
	{ "Bounty Target 4", "IG_BountyTarget_04" },
	{ "Bounty Target 6", "IG_BountyTarget_05" },
	{ "Bounty Target 6", "IG_BountyTarget_06" },
	{ "Brucie", "IG_Brucie2" },
	{ "Car Club Female", "a_f_y_carclub_01" },
	{ "Car Club Female 2", "A_F_Y_CarClub_02" },
	{ "Car Club Male 2", "A_M_Y_CarClub_02" },
	{ "Cartel Goons", "G_M_M_CartelGoons_01" },
	{ "Call Girl 1", "CSB_CallGirl_01" },
	{ "Call Girl 2", "CSB_CallGirl_02" },
	{ "Chef (CS)", "CSB_Chef_03" },
	{ "Chef (IG)", "IG_Chef_03" },
	{ "Clifford's Juggernaut", "u_m_y_juggernaut_01" },
	{ "Club Bartender Female", "S_F_Y_ClubBar_01" },
	{ "Club Bouncer", "S_M_Y_ClubBar_01" },
	{ "Club Customer Female", "A_F_Y_ClubCust_02" },
	{ "Club Customer Male", "A_M_Y_ClubCust_02" },
	{ "Dax (CS)", "CSB_Dax" },
	{ "Dax (IG)", "IG_Dax" },
	{ "Dance Party Coordinator", "S_F_Y_BeachBarStaff_01" },
	{ "Dima Popov", "ig_popov" },
	{ "DJ Aurelia", "IG_DJTalAurelia" },
	{ "DJ Black Madonna", "IG_DJBlaMadon" },
	{ "DJ Dixon", "IG_Dix" },
	{ "DJ Dixon's Manager", "IG_DJDixManager" },
	{ "DJ Fotios", "IG_DJSolFotios" },
	{ "DJ Ignazio", "IG_DJTalIgnazio" },
	{ "DJ Jakob", "IG_DJSolJakob" },
	{ "DJ Mike T", "IG_DJSolMike" },
	{ "DJ Palms Trax", "IG_IslDJ_03" },
	{ "DJ Pooh", "IG_MJO" },
	{ "DJ Rob T", "IG_DJSolRobT" },
	{ "DJ Rupert", "IG_DJBlamRupert" },
	{ "DJ Ryan S", "IG_DJBlamRyanS" },
	{ "Dr. Dre", "IG_ARY" },
	{ "Dr. Friedlander 2 (CS)", "CS_DrFriedlander_02" },
	{ "Dr. Friedlander 2 (IG)", "IG_DrFriedlander_02" },
	{ "Drug Dealer", "csb_drugdealer" },
	{ "English Dave", "IG_EnglishDave" },
	{ "Enrique", "G_M_M_CartelGuards_01" },
	{ "Entourage A", "IG_Entourage_A" },
	{ "Entourage B", "IG_Entourage_B" },
	{ "Female Club Dancer (Burlesque)", "U_F_Y_DanceBurl_01" },
	{ "Female Club Dancer (Leather)", "U_F_Y_DanceLthr_01" },
	{ "Female Club Dancer (Rave)", "U_F_Y_DanceRave_01" },
	{ "Field Worker", "S_M_M_FieldWorker_01" },
	{ "Furry (IG)", "IG_Furry" },
	{ "Fooliganz 1", "IG_Fooliganz_01" },
	{ "Fooliganz 2", "IG_Fooliganz_02" },
	{ "Fooliganz Goon (female)", "G_F_M_Fooliganz_01" },
	{ "Fooliganz Goon (male)", "G_M_M_Fooliganz_01" },
	{ "Friedlander Goon", "G_M_M_FriedlanderGoons_01" },
	{ "Generic DJ", "IG_DJGeneric_01" },
	{ "Generic Street (Male)", "A_F_M_GenStreet_01" },
	{ "Georgina Cheng", "IG_GeorginaCheng" },
	{ "Gerald", "csb_g" },
	{ "Golfer A", "IG_Golfer_A" },
	{ "Golfer B", "IG_Golfer_B" },
	{ "Goons 1", "G_M_M_Goons_01" },
	{ "Guadalope", "IG_Guadalope" },
	{ "Gustavo", "IG_Gustavo" },
	{ "Gun Van Seller", "IG_GunVanSeller" },
	{ "Hazmat Worker", "S_M_M_HazmatWorker_01" },
	{ "High Security", "S_M_M_HighSec_03" },
	{ "Hippy Leader (IG)", "IG_HippyLeader" },
	{ "Huang", "IG_Huang" },
	{ "Imani", "IG_Imani" },
	{ "Jackie", "IG_Jackie" },
	{ "Jamal Amir", "IG_JamalAmir" },
	{ "Jenette", "CSB_JenetteE" },
	{ "Jimmy Lovine", "IG_JIO" },
	{ "Juan Strickler aka El Rubio", "IG_JuanStrickler" },
	{ "Jodi Marshall (CS)", "CSB_JodiMarshall" },
	{ "Jodi Marhsall (IG)", "IG_JodiMarshall" },
	{ "Johnny Guns", "IG_Johnny_Guns" },
	{ "Kaylee", "IG_Kaylee" },
	{ "Labrat (CS)", "CSB_Labrat" },
	{ "Labrat (IG)", "IG_Labrat" },
	{ "Lacey Jonas", "IG_Lacey_Jones_02" },
	{ "Lil' Dee", "ig_lildee" },
	{ "Luchadora (CS)", "CSB_Luchadora" },
	{ "Luchadora (IG)", "IG_Luchadora" },
	{ "Mara Grande", "G_M_M_MaraGrande_01" },
	{ "Male Club Dancer (Burlesque)", "U_M_Y_DanceBurl_01" },
	{ "Male Club Dancer (Leather)", "U_M_Y_DanceLthr_01" },
	{ "Male Club Dancer (Rave)", "U_M_Y_DanceRave_01" },
	{ "Maxim Rashkovsky", "ig_rashcosvki" },
	{ "Mechanic", "IG_Mechanic_03" },
	{ "Miguel Madrazo", "IG_MiguelMadrazo" },
	{ "Mimi", "ig_mimi" },
	{ "Miranda", "U_F_M_Miranda_02" },
	{ "Moodymann", "IG_IslDJ_04" },
	{ "Moodymann's Girl 1", "IG_ISLDJ_04_E_01" },
	{ "Moodymann's Girl 2", "IG_ISLDJ_04_D_01" },
	{ "Moodymann's Girl 3", "IG_ISLDJ_04_D_02" },
	{ "Music Locker Barman", "S_F_Y_ClubBar_02" },
	{ "Music Locker Bouncer 1", "S_M_M_Bouncer_02" },
	{ "Music Locker Bouncer 2", "S_M_M_HighSec_04" },
	{ "Musician", "IG_Musician_00" },
	{ "Nervous Ron (CS)", "CS_NervousRon_02" },
	{ "Nervous Ron (IG)", "IG_NervousRon_02" },
	{ "Old Rich Guy", "IG_OldRichGuy" },
	{ "Oscar (CS)", "CSB_Oscar_02" },
	{ "Oscar (IG)", "IG_Oscar_02" },
	{ "Party Girl", "A_F_Y_Beach_02" },
	{ "Party Man 1", "A_M_O_Beach_02" },
	{ "Party Man 2", "A_M_Y_Beach_04" },
	{ "Party Promo", "IG_Party_Promo" },
	{ "Pavel", "IG_HelmsmanPavel" },
	{ "Pavel 2 (CS)", "CSB_HelmsmanPavel_02" },
	{ "Pavel 2 (IG)", "IG_HelmsmanPavel_02" },
	{ "Phil", "csb_undercover" },
	{ "Phoenicia Rackman", "csb_mrs_r" },
	{ "Race Manager", "s_m_m_raceorg_01" },
	{ "Rampa", "IG_IslDJ_00" },
	{ "Retail Stuff", "s_f_m_retailstaff_01" },
	{ "Req Officer", "IG_Req_Officer" },
	{ "Scott Storch", "IG_SSS" },
	{ "Security 5", "S_M_M_HighSec_05" },
	{ "Security A", "IG_Security_A" },
	{ "Sessanta", "csb_sessanta" },
	{ "Slasher", "g_m_m_slasher_01" },
	{ "Soloman", "IG_Sol" },
	{ "Soloman's Manager", "IG_DJSolManager" },
	{ "Sound Eng", "IG_SoundEng_00" },
	{ "Sound Eng 2", "S_M_M_StudioSouEng_02" },
	{ "Studio Assist 1", "S_F_M_StudioAssist_01" },
	{ "Studio Assist 2", "S_M_M_StudioAssist_02" },
	{ "Studio Party 01", "A_F_Y_StudioParty_01" },
	{ "Studio Party 1", "A_M_M_StudioParty_01" },
	{ "Studio Party 2", "A_F_Y_StudioParty_02" },
	{ "Studio Party Y", "A_M_Y_StudioParty_01" },
	{ "Studio Producer", "S_M_M_StudioProd_01" },
	{ "Sub Captain", "IG_SubCrewHead" },
	{ "Sub Crew", "S_M_M_SubCrew_01" },
	{ "Tale Of Us 1", "IG_TalCC" },
	{ "Tale Of Us 2", "IG_TalMM" },
	{ "Tatoo", "s_m_m_tattoo_01" },
	{ "Tatoocust", "a_m_y_tattoocust_01" },
	{ "Thornton", "IG_Thornton" },
	{ "Tony Prince", "IG_TonyPrince" },
	{ "Tyler Dixon", "IG_TylerDix_02" },
	{ "Vagos Leader", "IG_Vagos_Leader" },
	{ "Vernon", "IG_Vernon" },
	{ "Vincent", "IG_Vincent_2" },
	{ "Vincent 2", "IG_Vincent_4" },
	{ "VIP Charter Pilot", "IG_Pilot" },
	{ "Warehouse Technician", "S_M_Y_WareTech_01" },
	{ "Wendy", "IG_Wendy" },
	{ "West Security", "S_M_Y_WestSec_02" },
	{ "Yung Ancestor", "IG_Celeb_01" },
	{ "Generic Biker (Male)", "A_M_M_GenBiker_01" },
	{ "Generic Biker (Female)", "A_F_M_GenBiker_01" },
	{ "Generic Thug (Male)", "G_M_M_GenThug_01" },
	{ "Warehouse Boss", "IG_WarehouseBoss" },
	{ "Warehouse Worker (Male)", "S_M_M_Warehouse_01" },
	{ "Warehouse Worker (Female)", "S_F_M_Warehouse_01" },
	{ "Juggernaut 2", "U_M_Y_Juggernaut_02" },
	{ "Agent 2", "IG_Agent_02" },
	{ "Mason Duggan", "IG_Mason_Duggan" },
	{ "Yeti", "U_M_M_Yeti" },
	{ "Yulemonster", "U_M_M_YuleMonster" },
	{ "Yusuf Amir", "IG_YusufAmir" }
};
const std::vector<std::string> SKINS_ONLINE_CAPTIONS = captionsOf(SKINS_ONLINE_OPTIONS);
const std::vector<std::string> SKINS_ONLINE_VALUES = valuesOf(SKINS_ONLINE_OPTIONS);

// Reset Player Model On Death
const std::vector<std::string> SKINS_RESET_SKIN_ONDEATH_CAPTIONS{ "Restore On Respawn", "Compatibility Mode" }; // "Reset On Death", 
extern int ResetSkinOnDeathIdx;

/***
* METHODS
*/

bool applyChosenSkin(std::string skinName);

bool applyChosenSkin(DWORD model);

void reset_skin_globals();

bool process_skinchanger_menu();

bool process_skinchanger_category_menu();

bool process_prop_menu();

bool onconfirm_props_texture_menu(MenuItem<int> choice);

void onhighlight_props_texture_menu(MenuItem<int> choice);

//Save related stuff

bool skin_save_menu_interrupt();

bool skin_save_slot_menu_interrupt();

bool process_savedskin_menu();

bool process_savedskin_slot_menu(int slot);

bool spawn_saved_skin(int slot, std::string caption);

void save_current_skin(int slot);

void update_skin_features();

void add_skin_generic_settings(std::vector<StringPairSettingDBRow>* results);

void handle_generic_settings_skin(std::vector<StringPairSettingDBRow>* settings);

void add_player_skin_feature_enablements(std::vector<FeatureEnabledLocalDefinition>* results);

void onchange_skins_reset_skin_ondeath_index(int value, SelectFromListMenuItem* source);

void onchange_auto_apply_skin_saved_index(int value, SelectFromListMenuItem* source);