/*
Some of this code began its life as a part of GTA V SCRIPT HOOK SDK.
http://dev-c.com
(C) Alexander Blade 2015

It is now part of the Enhanced Native Trainer project.
https://github.com/gtav-ent/GTAV-EnhancedNativeTrainer
(C) Sondai SMith and fellow contributors 2015
*/

#pragma once

#include "..\..\inc\natives.h"
#include "..\..\inc\types.h"
#include "..\..\inc\enums.h"
#include "..\..\inc\main.h"
#include "..\ui_support\menu_functions.h"
#include "..\common\toggle_feature.h"
#include "..\storage\database.h"
#include "..\common\option_table.h"

const std::vector<std::string> MENU_WEAPON_CATEGORIES{ "Melee", "Handguns", "Submachine Guns", "Assault Rifles", "Shotguns", "Sniper Rifles", "Heavy Weapons", "Thrown Weapons" };

// Count: 20
const Option<std::string> MELEE_OPTIONS[] = {
	{ "WT_KNIFE", "WEAPON_KNIFE" },
	{ "WT_NGTSTK", "WEAPON_NIGHTSTICK" },
	{ "WT_HAMMER", "WEAPON_HAMMER" },
	{ "WT_BAT", "WEAPON_BAT" },
	{ "WT_BALL", "WEAPON_BALL" },
	{ "WT_DIGI", "WEAPON_DIGISCANNER" },
	{ "WT_GOLFCLUB", "WEAPON_GOLFCLUB" },
	{ "WT_CROWBAR", "WEAPON_CROWBAR" },
	{ "WT_BOTTLE", "WEAPON_BOTTLE" },
	{ "WT_DAGGER", "WEAPON_DAGGER" },
	{ "WT_HATCHET", "WEAPON_HATCHET" },
	{ "WT_KNUCKLE", "WEAPON_KNUCKLE" },
	{ "WT_MACHETE", "WEAPON_MACHETE" },
	{ "WT_FLASHLIGHT", "WEAPON_FLASHLIGHT" },
	{ "WT_SWBLADE", "WEAPON_SWITCHBLADE" },
	{ "WT_BATTLEAXE", "WEAPON_BATTLEAXE" },
	{ "WT_WRENCH", "WEAPON_WRENCH" },
	{ "WT_POOLCUE", "WEAPON_POOLCUE" },
	{ "WT_SHATCHET", "WEAPON_STONE_HATCHET" },
	{ "WT_METALDETECT", "WEAPON_METALDETECTOR" },
	{ "WT_HACKDEVICE", "WEAPON_HACKINGDEVICE" },
	{ "WT_CANDYCANE", "WEAPON_CANDYCANE" },
	{ "WT_STUNROD", "WEAPON_STUNROD" }
};
const std::vector<std::string> CAPTIONS_MELEE = captionsOf(MELEE_OPTIONS);
const std::vector<std::string> VALUES_MELEE = valuesOf(MELEE_OPTIONS);
// Count: 18
const Option<std::string> HANDGUN_OPTIONS[] = {
	{ "WT_PIST", "WEAPON_PISTOL" },
	{ "WT_PIST2", "WEAPON_PISTOL_MK2" },
	{ "WT_PIST_CBT", "WEAPON_COMBATPISTOL" },
	{ "WT_PIST_AP", "WEAPON_APPISTOL" },
	{ "WT_PIST_50", "WEAPON_PISTOL50" },
	{ "WT_SNSPISTOL", "WEAPON_SNSPISTOL" },
	{ "WT_SNSPISTOL2", "WEAPON_SNSPISTOL_MK2" },
	{ "WT_HEAVYPSTL", "WEAPON_HEAVYPISTOL" },
	{ "WT_VPISTOL", "WEAPON_VINTAGEPISTOL" },
	{ "WT_STUN", "WEAPON_STUNGUN" },
	{ "WT_FLAREGUN", "WEAPON_FLAREGUN" },
	{ "WT_MKPISTOL", "WEAPON_MARKSMANPISTOL" },
	{ "WT_REVOLVER", "WEAPON_REVOLVER" },
	{ "WT_REVOLVER2", "WEAPON_REVOLVER_MK2" },
	{ "WT_REV_DA", "WEAPON_DOUBLEACTION" },
	{ "WT_RAYPISTOL", "WEAPON_RAYPISTOL" },
	{ "WT_CERPST", "WEAPON_CERAMICPISTOL" },
	{ "WT_REV_NV", "WEAPON_NAVYREVOLVER" },
	{ "WT_GDGTPST", "WEAPON_GADGETPISTOL" },
	{ "WT_PISTOLXM3", "WEAPON_PISTOLXM3" }
};
const std::vector<std::string> CAPTIONS_HANDGUN = captionsOf(HANDGUN_OPTIONS);
const std::vector<std::string> VALUES_HANDGUN = valuesOf(HANDGUN_OPTIONS);
// Count: 10
const Option<std::string> SUBMACHINE_OPTIONS[] = {
	{ "WT_SMG_MCR", "WEAPON_MICROSMG" },
	{ "WT_SMG", "WEAPON_SMG" },
	{ "WT_SMG2", "WEAPON_SMG_MK2" },
	{ "WT_SMG_ASL", "WEAPON_ASSAULTSMG" },
	{ "WT_MG", "WEAPON_MG" },
	{ "WT_MG_CBT", "WEAPON_COMBATMG" },
	{ "WT_MG_CBT2", "WEAPON_COMBATMG_MK2" },
	{ "WT_GUSENBERG", "WEAPON_GUSENBERG" },
	{ "WT_COMBATPDW", "WEAPON_COMBATPDW" },
	{ "WT_MCHPIST", "WEAPON_MACHINEPISTOL" },
	{ "WT_MINISMG", "WEAPON_MINISMG" },
	{ "WT_TECPISTOL", "WEAPON_TECPISTOL" }
};
const std::vector<std::string> CAPTIONS_SUBMACHINE = captionsOf(SUBMACHINE_OPTIONS);
const std::vector<std::string> VALUES_SUBMACHINE = valuesOf(SUBMACHINE_OPTIONS);
// Count: 11
const Option<std::string> ASSAULT_OPTIONS[] = {
	{ "WT_RIFLE_ASL", "WEAPON_ASSAULTRIFLE" },
	{ "WT_RIFLE_ASL2", "WEAPON_ASSAULTRIFLE_MK2" },
	{ "WT_BULLRIFLE2", "WEAPON_BULLPUPRIFLE_MK2" },
	{ "WT_RIFLE_CBN", "WEAPON_CARBINERIFLE" },
	{ "WT_RIFLE_CBN2", "WEAPON_CARBINERIFLE_MK2" },
	{ "WT_RIFLE_ADV", "WEAPON_ADVANCEDRIFLE" },
	{ "WT_RIFLE_SCBN", "WEAPON_SPECIALCARBINE" },
	{ "WT_SPCARBINE2", "WEAPON_SPECIALCARBINE_MK2" },
	{ "WT_BULLRIFLE", "WEAPON_BULLPUPRIFLE" },
	{ "WT_CMPRIFLE", "WEAPON_COMPACTRIFLE" },
	{ "WT_RAYCARBINE", "WEAPON_RAYCARBINE" },
	{ "WT_MLTRYRFL", "WEAPON_MILITARYRIFLE" },
	{ "WT_HEAVYRIFLE", "WEAPON_HEAVYRIFLE" },
	{ "WT_TACRIFLE", "WEAPON_TACTICALRIFLE" },
	{ "WT_BATTLERIFLE", "WEAPON_BATTLERIFLE" }
};
const std::vector<std::string> CAPTIONS_ASSAULT = captionsOf(ASSAULT_OPTIONS);
const std::vector<std::string> VALUES_ASSAULT = valuesOf(ASSAULT_OPTIONS);
// Count: 9
const Option<std::string> SHOTGUN_OPTIONS[] = {
	{ "WT_SG_PMP", "WEAPON_PUMPSHOTGUN" },
	{ "WT_SG_PMP2", "WEAPON_PUMPSHOTGUN_MK2" },
	{ "WT_SG_SOF", "WEAPON_SAWNOFFSHOTGUN" },
	{ "WT_SG_BLP", "WEAPON_BULLPUPSHOTGUN" },
	{ "WT_SG_ASL", "WEAPON_ASSAULTSHOTGUN" },
	{ "WT_MUSKET", "WEAPON_MUSKET" },
	{ "WT_HVYSHOT", "WEAPON_HEAVYSHOTGUN" },
	{ "WT_DBSHGN", "WEAPON_DBSHOTGUN" },
	{ "WT_AUTOSHGN", "WEAPON_AUTOSHOTGUN" },
	{ "WT_CMBSHGN", "WEAPON_COMBATSHOTGUN" }
};
const std::vector<std::string> CAPTIONS_SHOTGUN = captionsOf(SHOTGUN_OPTIONS);
const std::vector<std::string> VALUES_SHOTGUN = valuesOf(SHOTGUN_OPTIONS);
// Count: 3
const Option<std::string> SNIPER_OPTIONS[] = {
	{ "WT_SNIP_RIF", "WEAPON_SNIPERRIFLE" },
	{ "WT_SNIP_HVY", "WEAPON_HEAVYSNIPER" },
	{ "WT_SNIP_HVY2", "WEAPON_HEAVYSNIPER_MK2" },
	{ "WT_MKRIFLE", "WEAPON_MARKSMANRIFLE" },
	{ "WT_MKRIFLE2", "WEAPON_MARKSMANRIFLE_MK2" },
	{ "WT_PRCSRIFLE", "WEAPON_PRECISIONRIFLE" }
};
const std::vector<std::string> CAPTIONS_SNIPER = captionsOf(SNIPER_OPTIONS);
const std::vector<std::string> VALUES_SNIPER = valuesOf(SNIPER_OPTIONS);
// Count: 9
const Option<std::string> HEAVY_OPTIONS[] = {
	{ "WT_GL", "WEAPON_GRENADELAUNCHER" },
	{ "WT_RPG", "WEAPON_RPG" },
	{ "WT_MINIGUN", "WEAPON_MINIGUN" },
	{ "WT_FIREWRK", "WEAPON_FIREWORK" },
	{ "WT_RAILGUN", "WEAPON_RAILGUN" },
	{ "WT_HOMLNCH", "WEAPON_HOMINGLAUNCHER" },
	{ "WT_CMPGL", "WEAPON_COMPACTLAUNCHER" },
	{ "WT_RAYMINIGUN", "WEAPON_RAYMINIGUN" },
	{ "WT_EMPL", "WEAPON_EMPLAUNCHER" },
	{ "WT_RAILGUNXM3", "WEAPON_RAILGUNXM3" },
	{ "WT_SNOWLNCHR", "WEAPON_SNOWLAUNCHER" }
};
const std::vector<std::string> CAPTIONS_HEAVY = captionsOf(HEAVY_OPTIONS);
const std::vector<std::string> VALUES_HEAVY = valuesOf(HEAVY_OPTIONS);
// Count: 11
const Option<std::string> THROWN_OPTIONS[] = {
	{ "WT_GNADE", "WEAPON_GRENADE" },
	{ "WT_GNADE_STK", "WEAPON_STICKYBOMB" },
	{ "WT_PRXMINE", "WEAPON_PROXMINE" },
	{ "WT_BZGAS", "WEAPON_SMOKEGRENADE" },
	{ "WT_MOLOTOV", "WEAPON_MOLOTOV" },
	{ "WT_FIRE", "WEAPON_FIREEXTINGUISHER" },
	{ "WT_PETROL", "WEAPON_PETROLCAN" },
	{ "WT_SNWBALL", "WEAPON_SNOWBALL" },
	{ "WT_FLARE", "WEAPON_FLARE" },
	{ "WT_PIPEBOMB", "WEAPON_PIPEBOMB" },
	{ "WT_HAZARDCAN", "WEAPON_HAZARDCAN" },
	{ "WT_FERTILIZERCAN", "WEAPON_FERTILIZERCAN" },
	{ "WT_ACIDPACKAGE", "WEAPON_ACIDPACKAGE" }
};
const std::vector<std::string> CAPTIONS_THROWN = captionsOf(THROWN_OPTIONS);
const std::vector<std::string> VALUES_THROWN = valuesOf(THROWN_OPTIONS);


const std::vector<std::string> VOV_WEAPON_CAPTIONS[] = {CAPTIONS_MELEE, CAPTIONS_HANDGUN, CAPTIONS_SUBMACHINE, CAPTIONS_ASSAULT, CAPTIONS_SHOTGUN, CAPTIONS_SNIPER, CAPTIONS_HEAVY, CAPTIONS_THROWN};
const std::vector<std::string> VOV_WEAPON_VALUES[] = {VALUES_MELEE, VALUES_HANDGUN, VALUES_SUBMACHINE, VALUES_ASSAULT, VALUES_SHOTGUN, VALUES_SNIPER, VALUES_HEAVY, VALUES_THROWN};

//Weapon tints
constexpr Option<int> TINT_OPTIONS[] = {
	{ "Normal", 0 }, { "Green", 1 }, { "Gold", 2 }, { "Pink", 3 },
	{ "Army", 4 }, { "LSPD", 5 }, { "Orange", 6 }, { "Platinum", 7 }
};
const std::vector<std::string> CAPTIONS_TINT = captionsOf(TINT_OPTIONS);
const std::vector<int> VALUES_TINT = valuesOf(TINT_OPTIONS);

//Weapon tints for MK2 weapons
const std::vector<std::string> CAPTIONS_TINT_MK2{ "Classic Black", "Classic Gray", "Classic Two-Tone", "Classic White", "Classic Beige", "Classic Green", "Classic Blue", "Classic Earth", "Classic Brown & Black", "Red Contrast", "Blue Contrast", "Yellow Contrast", "Orange Contrast", "Bold Pink", "Bold Purple & Yellow", "Bold Orange", "Bold Green & Purple", "Bold Red Features", "Bold Green Features", "Bold Cyan Features", "Bold Yellow Features", "Bold Red & White", "Bold Blue & White", "Metallic Gold", "Metallic Platinum", "Metallic Gray & Lilca", "Metallic Purple & Lime", "Metallic Red", "Metallic Green", "Metallic Blue", "Metallic White & Aqua", "Metallic Red & Yellow" };

//Pistols
const Option<std::string> ATTACH_PISTOL_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_PISTOL_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_PISTOL_CLIP_02" },
	{ "WCT_FLASH", "COMPONENT_AT_PI_FLSH" },
	{ "WCT_SUPP", "COMPONENT_AT_PI_SUPP_02" },
	{ "WCT_VAR_GOLD", "COMPONENT_PISTOL_VARMOD_LUXE" }
};
const std::vector<std::string> CAPTIONS_ATTACH_PISTOL = captionsOf(ATTACH_PISTOL_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_PISTOL = valuesOf(ATTACH_PISTOL_OPTIONS);

const Option<std::string> ATTACH_COMBATPISTOL_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_COMBATPISTOL_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_COMBATPISTOL_CLIP_02" },
	{ "WCT_FLASH", "COMPONENT_AT_PI_FLSH" },
	{ "WCT_SUPP", "COMPONENT_AT_PI_SUPP" },
	{ "WCT_VAR_GOLD", "COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER" }
};
const std::vector<std::string> CAPTIONS_ATTACH_COMBATPISTOL = captionsOf(ATTACH_COMBATPISTOL_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_COMBATPISTOL = valuesOf(ATTACH_COMBATPISTOL_OPTIONS);

const Option<std::string> ATTACH_APPISTOL_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_APPISTOL_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_APPISTOL_CLIP_02" },
	{ "WCT_FLASH", "COMPONENT_AT_PI_FLSH" },
	{ "WCT_SUPP", "COMPONENT_AT_PI_SUPP" },
	{ "WCT_VAR_METAL", "COMPONENT_APPISTOL_VARMOD_LUXE" }
};
const std::vector<std::string> CAPTIONS_ATTACH_APPISTOL = captionsOf(ATTACH_APPISTOL_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_APPISTOL = valuesOf(ATTACH_APPISTOL_OPTIONS);

const Option<std::string> ATTACH_PISTOL50_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_PISTOL50_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_PISTOL50_CLIP_02" },
	{ "WCT_FLASH", "COMPONENT_AT_PI_FLSH" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP_02" },
	{ "WCT_VAR_SIL", "COMPONENT_PISTOL50_VARMOD_LUXE" }
};
const std::vector<std::string> CAPTIONS_ATTACH_PISTOL50 = captionsOf(ATTACH_PISTOL50_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_PISTOL50 = valuesOf(ATTACH_PISTOL50_OPTIONS);

//SMGs
const Option<std::string> ATTACH_MICROSMG_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_MICROSMG_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_MICROSMG_CLIP_02" },
	{ "WCT_FLASH", "COMPONENT_AT_PI_FLSH" },
	{ "WCT_SCOPE_MAC", "COMPONENT_AT_SCOPE_MACRO" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP_02" },
	{ "WCT_VAR_GOLD", "COMPONENT_MICROSMG_VARMOD_LUXE" }
};
const std::vector<std::string> CAPTIONS_ATTACH_MICROSMG = captionsOf(ATTACH_MICROSMG_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_MICROSMG = valuesOf(ATTACH_MICROSMG_OPTIONS);

const Option<std::string> ATTACH_SMG_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_SMG_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_SMG_CLIP_02" },
	{ "WCT_CLIP_DRM", "COMPONENT_SMG_CLIP_03" },
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_SCOPE_MAC", "COMPONENT_AT_SCOPE_MACRO_02" },
	{ "WCT_SUPP", "COMPONENT_AT_PI_SUPP" },
	{ "WCT_VAR_GOLD", "COMPONENT_SMG_VARMOD_LUXE" }
};
const std::vector<std::string> CAPTIONS_ATTACH_SMG = captionsOf(ATTACH_SMG_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_SMG = valuesOf(ATTACH_SMG_OPTIONS);

const Option<std::string> ATTACH_ASSAULTSMG_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_ASSAULTSMG_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_ASSAULTSMG_CLIP_02" },
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_SCOPE_MAC", "COMPONENT_AT_SCOPE_MACRO" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP_02" },
	{ "WCT_VAR_GOLD", "COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER" }
};
const std::vector<std::string> CAPTIONS_ATTACH_ASSAULTSMG = captionsOf(ATTACH_ASSAULTSMG_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_ASSAULTSMG = valuesOf(ATTACH_ASSAULTSMG_OPTIONS);

//Rifles
const Option<std::string> ATTACH_ASSAULTRIFLE_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_ASSAULTRIFLE_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_ASSAULTRIFLE_CLIP_02" },
	{ "WCT_CLIP_DRM", "COMPONENT_ASSAULTRIFLE_CLIP_03" },
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_SCOPE_MAC", "COMPONENT_AT_SCOPE_MACRO" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP_02" },
	{ "WCT_GRIP", "COMPONENT_AT_AR_AFGRIP" },
	{ "WCT_VAR_GOLD", "COMPONENT_ASSAULTRIFLE_VARMOD_LUXE" }
};
const std::vector<std::string> CAPTIONS_ATTACH_ASSAULTRIFLE = captionsOf(ATTACH_ASSAULTRIFLE_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_ASSAULTRIFLE = valuesOf(ATTACH_ASSAULTRIFLE_OPTIONS);

const Option<std::string> ATTACH_CARBINERIFLE_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_CARBINERIFLE_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_CARBINERIFLE_CLIP_02" },
	{ "WCT_CLIP_DRM", "COMPONENT_CARBINERIFLE_CLIP_03" },
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_SCOPE_MAC", "COMPONENT_AT_SCOPE_MEDIUM" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP" },
	{ "WCT_GRIP", "COMPONENT_AT_AR_AFGRIP" },
	{ "WCT_VAR_GOLD", "COMPONENT_CARBINERIFLE_VARMOD_LUXE" }
};
const std::vector<std::string> CAPTIONS_ATTACH_CARBINERIFLE = captionsOf(ATTACH_CARBINERIFLE_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_CARBINERIFLE = valuesOf(ATTACH_CARBINERIFLE_OPTIONS);

const Option<std::string> ATTACH_ADVANCEDRIFLE_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_ADVANCEDRIFLE_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_ADVANCEDRIFLE_CLIP_02" },
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_SCOPE_MAC", "COMPONENT_AT_SCOPE_SMALL" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP" },
	{ "WCT_VAR_METAL", "COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE" }
};
const std::vector<std::string> CAPTIONS_ATTACH_ADVANCEDRIFLE = captionsOf(ATTACH_ADVANCEDRIFLE_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_ADVANCEDRIFLE = valuesOf(ATTACH_ADVANCEDRIFLE_OPTIONS);

//Machine Guns
const Option<std::string> ATTACH_MG_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_MG_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_MG_CLIP_02" },
	{ "WCT_SCOPE_MAC", "COMPONENT_AT_SCOPE_SMALL_02" },
	{ "WCT_VAR_GOLD", "COMPONENT_MG_VARMOD_LOWRIDER" }
};
const std::vector<std::string> CAPTIONS_ATTACH_MG = captionsOf(ATTACH_MG_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_MG = valuesOf(ATTACH_MG_OPTIONS);

const Option<std::string> ATTACH_COMBATMG_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_COMBATMG_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_COMBATMG_CLIP_02" },
	{ "WCT_SCOPE_MAC", "COMPONENT_AT_SCOPE_MEDIUM" },
	{ "WCT_GRIP", "COMPONENT_AT_AR_AFGRIP" },
	{ "WCT_VAR_ETCHM", "COMPONENT_COMBATMG_VARMOD_LOWRIDER" }
};
const std::vector<std::string> CAPTIONS_ATTACH_COMBATMG = captionsOf(ATTACH_COMBATMG_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_COMBATMG = valuesOf(ATTACH_COMBATMG_OPTIONS);

//Shotguns
const Option<std::string> ATTACH_PUMPSHOTGUN_OPTIONS[] = {
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_SUPP", "COMPONENT_AT_SR_SUPP" },
	{ "WCT_VAR_GOLD", "COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER" }
};
const std::vector<std::string> CAPTIONS_ATTACH_PUMPSHOTGUN = captionsOf(ATTACH_PUMPSHOTGUN_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_PUMPSHOTGUN = valuesOf(ATTACH_PUMPSHOTGUN_OPTIONS);

const Option<std::string> ATTACH_SAWNOFF_OPTIONS[] = {
	{ "WCT_VAR_METAL", "COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE" }
};
const std::vector<std::string> CAPTIONS_ATTACH_SAWNOFF = captionsOf(ATTACH_SAWNOFF_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_SAWNOFF = valuesOf(ATTACH_SAWNOFF_OPTIONS);

const Option<std::string> ATTACH_ASSAULTSHOTGUN_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_ASSAULTSHOTGUN_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_ASSAULTSHOTGUN_CLIP_02" },
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP" },
	{ "WCT_GRIP", "COMPONENT_AT_AR_AFGRIP" }
};
const std::vector<std::string> CAPTIONS_ATTACH_ASSAULTSHOTGUN = captionsOf(ATTACH_ASSAULTSHOTGUN_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_ASSAULTSHOTGUN = valuesOf(ATTACH_ASSAULTSHOTGUN_OPTIONS);

const Option<std::string> ATTACH_BULLPUPSHOTGUN_OPTIONS[] = {
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP_02" },
	{ "WCT_GRIP", "COMPONENT_AT_AR_AFGRIP" }
};
const std::vector<std::string> CAPTIONS_ATTACH_BULLPUPSHOTGUN = captionsOf(ATTACH_BULLPUPSHOTGUN_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_BULLPUPSHOTGUN = valuesOf(ATTACH_BULLPUPSHOTGUN_OPTIONS);

//Sniper Rifles
const Option<std::string> ATTACH_SNIPERRIFLE_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_SNIPERRIFLE_CLIP_01" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP_02" },
	{ "WCT_SCOPE_LRG", "COMPONENT_AT_SCOPE_LARGE" },
	{ "WCT_SCOPE_MAX", "COMPONENT_AT_SCOPE_MAX" },
	{ "WCT_VAR_WOOD", "COMPONENT_SNIPERRIFLE_VARMOD_LUXE" }
};
const std::vector<std::string> CAPTIONS_ATTACH_SNIPERRIFLE = captionsOf(ATTACH_SNIPERRIFLE_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_SNIPERRIFLE = valuesOf(ATTACH_SNIPERRIFLE_OPTIONS);

const Option<std::string> ATTACH_HEAVYSNIPER_OPTIONS[] = {
	{ "WCT_SCOPE_LRG", "COMPONENT_AT_SCOPE_LARGE" },
	{ "WCT_SCOPE_MAX", "COMPONENT_AT_SCOPE_MAX" }
};
const std::vector<std::string> CAPTIONS_ATTACH_HEAVYSNIPER = captionsOf(ATTACH_HEAVYSNIPER_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_HEAVYSNIPER = valuesOf(ATTACH_HEAVYSNIPER_OPTIONS);

//Heavy Weapons
const Option<std::string> ATTACH_GRENADELAUNCHER_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_GRENADELAUNCHER_CLIP_01" },
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_GRIP", "COMPONENT_AT_AR_AFGRIP" },
	{ "WCT_SCOPE_MAC", "COMPONENT_AT_SCOPE_SMALL" }
};
const std::vector<std::string> CAPTIONS_ATTACH_GRENADELAUNCHER = captionsOf(ATTACH_GRENADELAUNCHER_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_GRENADELAUNCHER = valuesOf(ATTACH_GRENADELAUNCHER_OPTIONS);

const Option<std::string> ATTACH_HEAVYRIFLE_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_HEAVYRIFLE_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_HEAVYRIFLE_CLIP_02" },
	{ "WCT_HVYRFLE_SIG", "COMPONENT_HEAVYRIFLE_SIGHT_01" },
	{ "WCT_SCOPE_LRG", "COMPONENT_AT_SCOPE_MEDIUM" },
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP" },
	{ "WCT_GRIP", "COMPONENT_AT_AR_AFGRIP" },
	{ "WCT_VAR_FAM", "COMPONENT_HEAVYRIFLE_CAMO1" }
};
const std::vector<std::string> CAPTIONS_ATTACH_HEAVYRIFLE = captionsOf(ATTACH_HEAVYRIFLE_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_HEAVYRIFLE = valuesOf(ATTACH_HEAVYRIFLE_OPTIONS);


//DLC Weapons
const Option<std::string> ATTACH_BULLPUPRIFLE_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_BULLPUPRIFLE_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_BULLPUPRIFLE_CLIP_02" },
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_SCOPE_MAC", "COMPONENT_AT_SCOPE_SMALL" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP" },
	{ "WCT_GRIP", "COMPONENT_AT_AR_AFGRIP" },
	{ "WCT_VAR_METAL", "COMPONENT_BULLPUPRIFLE_VARMOD_LOW" }
};
const std::vector<std::string> CAPTIONS_ATTACH_BULLPUPRIFLE = captionsOf(ATTACH_BULLPUPRIFLE_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_BULLPUPRIFLE = valuesOf(ATTACH_BULLPUPRIFLE_OPTIONS);

const Option<std::string> ATTACH_COMBATPDW_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_COMBATPDW_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_COMBATPDW_CLIP_02" },
	{ "WCT_CLIP_DRM", "COMPONENT_COMBATPDW_CLIP_03" },
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_GRIP", "COMPONENT_AT_AR_AFGRIP" },
	{ "WCT_SCOPE_SML", "COMPONENT_AT_SCOPE_SMALL" }
};
const std::vector<std::string> CAPTIONS_ATTACH_COMBATPDW = captionsOf(ATTACH_COMBATPDW_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_COMBATPDW = valuesOf(ATTACH_COMBATPDW_OPTIONS);

const Option<std::string> ATTACH_COMPACTRIFLE_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_COMPACTRIFLE_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_COMPACTRIFLE_CLIP_02" },
	{ "WCT_CLIP_DRM", "COMPONENT_COMPACTRIFLE_CLIP_03" }
};
const std::vector<std::string> CAPTIONS_ATTACH_COMPACTRIFLE = captionsOf(ATTACH_COMPACTRIFLE_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_COMPACTRIFLE = valuesOf(ATTACH_COMPACTRIFLE_OPTIONS);

const Option<std::string> ATTACH_GUSENBERG_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_GUSENBERG_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_GUSENBERG_CLIP_02" }
};
const std::vector<std::string> CAPTIONS_ATTACH_GUSENBERG = captionsOf(ATTACH_GUSENBERG_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_GUSENBERG = valuesOf(ATTACH_GUSENBERG_OPTIONS);

const Option<std::string> ATTACH_HEAVYPISTOL_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_HEAVYPISTOL_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_HEAVYPISTOL_CLIP_02" },
	{ "WCT_FLASH", "COMPONENT_AT_PI_FLSH" },
	{ "WCT_SUPP", "COMPONENT_AT_PI_SUPP" },
	{ "WCT_VAR_WOOD", "COMPONENT_HEAVYPISTOL_VARMOD_LUXE" }
};
const std::vector<std::string> CAPTIONS_ATTACH_HEAVYPISTOL = captionsOf(ATTACH_HEAVYPISTOL_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_HEAVYPISTOL = valuesOf(ATTACH_HEAVYPISTOL_OPTIONS);

const Option<std::string> ATTACH_HEAVYSHOTGUN_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_HEAVYSHOTGUN_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_HEAVYSHOTGUN_CLIP_02" },
	{ "WCT_CLIP_DRM", "COMPONENT_HEAVYSHOTGUN_CLIP_03" },
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP_02" },
	{ "WCT_GRIP", "COMPONENT_AT_AR_AFGRIP" }
};
const std::vector<std::string> CAPTIONS_ATTACH_HEAVYSHOTGUN = captionsOf(ATTACH_HEAVYSHOTGUN_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_HEAVYSHOTGUN = valuesOf(ATTACH_HEAVYSHOTGUN_OPTIONS);

const Option<std::string> ATTACH_KNUCKLES_OPTIONS[] = {
	{ "WCT_KNUCK_01", "COMPONENT_KNUCKLE_VARMOD_BASE" },
	{ "WCT_KNUCK_02", "COMPONENT_KNUCKLE_VARMOD_PIMP" },
	{ "WCT_KNUCK_BG", "COMPONENT_KNUCKLE_VARMOD_BALLAS" },
	{ "WCT_KNUCK_DLR", "COMPONENT_KNUCKLE_VARMOD_DOLLAR" },
	{ "WCT_KNUCK_DMD", "COMPONENT_KNUCKLE_VARMOD_DIAMOND" },
	{ "WCT_KNUCK_HT", "COMPONENT_KNUCKLE_VARMOD_HATE" },
	{ "WCT_KNUCK_LV", "COMPONENT_KNUCKLE_VARMOD_LOVE" },
	{ "WCT_KNUCK_PC", "COMPONENT_KNUCKLE_VARMOD_PLAYER" },
	{ "WCT_KNUCK_SLG", "COMPONENT_KNUCKLE_VARMOD_KING" },
	{ "WCT_KNUCK_VG", "COMPONENT_KNUCKLE_VARMOD_VAGOS" }
};
const std::vector<std::string> CAPTIONS_ATTACH_KNUCKLES = captionsOf(ATTACH_KNUCKLES_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_KNUCKLES = valuesOf(ATTACH_KNUCKLES_OPTIONS);

const Option<std::string> ATTACH_MACHINEPISTOL_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_MACHINEPISTOL_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_MACHINEPISTOL_CLIP_02" },
	{ "WCT_CLIP_DRM", "COMPONENT_MACHINEPISTOL_CLIP_03" },
	{ "WCT_SUPP", "COMPONENT_AT_PI_SUPP" }
};
const std::vector<std::string> CAPTIONS_ATTACH_MACHINEPISTOL = captionsOf(ATTACH_MACHINEPISTOL_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_MACHINEPISTOL = valuesOf(ATTACH_MACHINEPISTOL_OPTIONS);

const Option<std::string> ATTACH_MARKSMANRIFLE_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_MARKSMANRIFLE_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_MARKSMANRIFLE_CLIP_02" },
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP" },
	{ "WCT_GRIP", "COMPONENT_AT_AR_AFGRIP" },
	{ "WCT_VAR_GOLD", "COMPONENT_MARKSMANRIFLE_VARMOD_LUXE" }
};
const std::vector<std::string> CAPTIONS_ATTACH_MARKSMANRIFLE = captionsOf(ATTACH_MARKSMANRIFLE_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_MARKSMANRIFLE = valuesOf(ATTACH_MARKSMANRIFLE_OPTIONS);

const Option<std::string> ATTACH_MINISMG_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_MINISMG_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_MINISMG_CLIP_02" }
};
const std::vector<std::string> CAPTIONS_ATTACH_MINISMG = captionsOf(ATTACH_MINISMG_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_MINISMG = valuesOf(ATTACH_MINISMG_OPTIONS);

const Option<std::string> ATTACH_REVOLVER_OPTIONS[] = {
	{ "WCT_REV_VARB", "COMPONENT_REVOLVER_VARMOD_BOSS" },
	{ "WCT_REV_VARG", "COMPONENT_REVOLVER_VARMOD_GOON" }
};
const std::vector<std::string> CAPTIONS_ATTACH_REVOLVER = captionsOf(ATTACH_REVOLVER_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_REVOLVER = valuesOf(ATTACH_REVOLVER_OPTIONS);

const Option<std::string> ATTACH_SNSPISTOL_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_SNSPISTOL_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_SNSPISTOL_CLIP_02" },
	{ "WCT_VAR_WOOD", "COMPONENT_SNSPISTOL_VARMOD_LOWRIDER" }
};
const std::vector<std::string> CAPTIONS_ATTACH_SNSPISTOL = captionsOf(ATTACH_SNSPISTOL_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_SNSPISTOL = valuesOf(ATTACH_SNSPISTOL_OPTIONS);

const Option<std::string> ATTACH_SPECIALCARBINE_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_SPECIALCARBINE_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_SPECIALCARBINE_CLIP_02" },
	{ "WCT_CLIP_DRM", "COMPONENT_SPECIALCARBINE_CLIP_03" },
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_SCOPE_MAC", "COMPONENT_AT_SCOPE_MEDIUM" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP_02" },
	{ "WCT_GRIP", "COMPONENT_AT_AR_AFGRIP" },
	{ "WCT_VAR_ETCHM", "COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER" }
};
const std::vector<std::string> CAPTIONS_ATTACH_SPECIALCARBINE = captionsOf(ATTACH_SPECIALCARBINE_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_SPECIALCARBINE = valuesOf(ATTACH_SPECIALCARBINE_OPTIONS);

const Option<std::string> ATTACH_SWITCHBLADE_OPTIONS[] = {
	{ "WCT_SB_BASE", "COMPONENT_SWITCHBLADE_VARMOD_BASE" },
	{ "WCT_SB_VAR1", "COMPONENT_SWITCHBLADE_VARMOD_VAR1" },
	{ "WCT_SB_VAR2", "COMPONENT_SWITCHBLADE_VARMOD_VAR2" }
};
const std::vector<std::string> CAPTIONS_ATTACH_SWITCHBLADE = captionsOf(ATTACH_SWITCHBLADE_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_SWITCHBLADE = valuesOf(ATTACH_SWITCHBLADE_OPTIONS);

const Option<std::string> ATTACH_VINTAGEPISTOL_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_VINTAGEPISTOL_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_VINTAGEPISTOL_CLIP_02" },
	{ "WCT_SUPP", "COMPONENT_AT_PI_SUPP" }
};
const std::vector<std::string> CAPTIONS_ATTACH_VINTAGEPISTOL = captionsOf(ATTACH_VINTAGEPISTOL_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_VINTAGEPISTOL = valuesOf(ATTACH_VINTAGEPISTOL_OPTIONS);

const Option<std::string> ATTACH_WEAPON_TECPISTOL_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_TECPISTOL_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_TECPISTOL_CLIP_02" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP_02" },
	{ "WCT_SCOPE_MAC2", "COMPONENT_AT_SCOPE_MACRO" }
};
const std::vector<std::string> CAPTIONS_ATTACH_WEAPON_TECPISTOL = captionsOf(ATTACH_WEAPON_TECPISTOL_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_WEAPON_TECPISTOL = valuesOf(ATTACH_WEAPON_TECPISTOL_OPTIONS);

/*Gun Running DLC*/
const Option<std::string> ATTACH_PISTOLMK2_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_PISTOL_MK2_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_PISTOL_MK2_CLIP_02" },
	{ "WCT_CLIP_TR", "COMPONENT_PISTOL_MK2_CLIP_TRACER" },
	{ "WCT_CLIP_INC", "COMPONENT_PISTOL_MK2_CLIP_INCENDIARY" },
	{ "WCT_CLIP_HP", "COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT" },
	{ "WCT_CLIP_FMJ", "COMPONENT_PISTOL_MK2_CLIP_FMJ" },
	{ "WCT_SCOPE_PI", "COMPONENT_AT_PI_RAIL" },
	{ "WCT_FLASH", "COMPONENT_AT_PI_FLSH_02" },
	{ "WCT_SUPP", "COMPONENT_AT_PI_SUPP_02" },
	{ "WCT_COMP", "COMPONENT_AT_PI_COMP" },
	{ "WCT_CAMO_1", "COMPONENT_PISTOL_MK2_CAMO" },
	{ "WCT_CAMO_2", "COMPONENT_PISTOL_MK2_CAMO_02" },
	{ "WCT_CAMO_3", "COMPONENT_PISTOL_MK2_CAMO_03" },
	{ "WCT_CAMO_4", "COMPONENT_PISTOL_MK2_CAMO_04" },
	{ "WCT_CAMO_5", "COMPONENT_PISTOL_MK2_CAMO_05" },
	{ "WCT_CAMO_6", "COMPONENT_PISTOL_MK2_CAMO_06" },
	{ "WCT_CAMO_7", "COMPONENT_PISTOL_MK2_CAMO_07" },
	{ "WCT_CAMO_8", "COMPONENT_PISTOL_MK2_CAMO_08" },
	{ "WCT_CAMO_9", "COMPONENT_PISTOL_MK2_CAMO_09" },
	{ "WCT_CAMO_10", "COMPONENT_PISTOL_MK2_CAMO_10" },
	{ "WCT_CAMO_IND", "COMPONENT_PISTOL_MK2_CAMO_IND_01" },
	{ "WCT_CAMO_1", "COMPONENT_PISTOL_MK2_CAMO_SLIDE" },
	{ "WCT_CAMO_2", "COMPONENT_PISTOL_MK2_CAMO_02_SLIDE" },
	{ "WCT_CAMO_3", "COMPONENT_PISTOL_MK2_CAMO_03_SLIDE" },
	{ "WCT_CAMO_4", "COMPONENT_PISTOL_MK2_CAMO_04_SLIDE" },
	{ "WCT_CAMO_5", "COMPONENT_PISTOL_MK2_CAMO_05_SLIDE" },
	{ "WCT_CAMO_6", "COMPONENT_PISTOL_MK2_CAMO_06_SLIDE" },
	{ "WCT_CAMO_7", "COMPONENT_PISTOL_MK2_CAMO_07_SLIDE" },
	{ "WCT_CAMO_8", "COMPONENT_PISTOL_MK2_CAMO_08_SLIDE" },
	{ "WCT_CAMO_9", "COMPONENT_PISTOL_MK2_CAMO_09_SLIDE" },
	{ "WCT_CAMO_10", "COMPONENT_PISTOL_MK2_CAMO_10_SLIDE" },
	{ "WCT_CAMO_IND", "COMPONENT_PISTOL_MK2_CAMO_IND_01_SLIDE" }
};
const std::vector<std::string> CAPTIONS_ATTACH_PISTOLMK2 = captionsOf(ATTACH_PISTOLMK2_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_PISTOLMK2 = valuesOf(ATTACH_PISTOLMK2_OPTIONS);

const Option<std::string> ATTACH_SMGMK2_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_SMG_MK2_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_SMG_MK2_CLIP_02" },
	{ "WCT_CLIP_TR", "COMPONENT_SMG_MK2_CLIP_TRACER" },
	{ "WCT_CLIP_INC", "COMPONENT_SMG_MK2_CLIP_INCENDIARY" },
	{ "WCT_CLIP_HP", "COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT" },
	{ "WCT_CLIP_FMJ", "COMPONENT_SMG_MK2_CLIP_FMJ" },
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_HOLO", "COMPONENT_AT_SIGHTS_SMG" },
	{ "WCT_SCOPE_MAC2", "COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2" },
	{ "WCT_SCOPE_SML2", "COMPONENT_AT_SCOPE_SMALL_SMG_MK2" },
	{ "WCT_SUPP", "COMPONENT_AT_PI_SUPP" },
	{ "WCT_MUZZ1", "COMPONENT_AT_MUZZLE_01" },
	{ "WCT_MUZZ2", "COMPONENT_AT_MUZZLE_02" },
	{ "WCT_MUZZ3", "COMPONENT_AT_MUZZLE_03" },
	{ "WCT_MUZZ4", "COMPONENT_AT_MUZZLE_04" },
	{ "WCT_MUZZ5", "COMPONENT_AT_MUZZLE_05" },
	{ "WCT_MUZZ6", "COMPONENT_AT_MUZZLE_06" },
	{ "WCT_MUZZ7", "COMPONENT_AT_MUZZLE_07" },
	{ "WCT_BARR", "COMPONENT_AT_SB_BARREL_01" },
	{ "WCT_BARR2", "COMPONENT_AT_SB_BARREL_02" },
	{ "WCT_CAMO_1", "COMPONENT_SMG_MK2_CAMO" },
	{ "WCT_CAMO_2", "COMPONENT_SMG_MK2_CAMO_02" },
	{ "WCT_CAMO_3", "COMPONENT_SMG_MK2_CAMO_03" },
	{ "WCT_CAMO_4", "COMPONENT_SMG_MK2_CAMO_04" },
	{ "WCT_CAMO_5", "COMPONENT_SMG_MK2_CAMO_05" },
	{ "WCT_CAMO_6", "COMPONENT_SMG_MK2_CAMO_06" },
	{ "WCT_CAMO_7", "COMPONENT_SMG_MK2_CAMO_07" },
	{ "WCT_CAMO_8", "COMPONENT_SMG_MK2_CAMO_08" },
	{ "WCT_CAMO_9", "COMPONENT_SMG_MK2_CAMO_09" },
	{ "WCT_CAMO_10", "COMPONENT_SMG_MK2_CAMO_10" },
	{ "WCT_CAMO_IND", "COMPONENT_SMG_MK2_CAMO_IND_01" }
};
const std::vector<std::string> CAPTIONS_ATTACH_SMGMK2 = captionsOf(ATTACH_SMGMK2_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_SMGMK2 = valuesOf(ATTACH_SMGMK2_OPTIONS);

const Option<std::string> ATTACH_ASSAULTRIFLEMK2_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_02" },
	{ "WCT_CLIP_TR", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER" },
	{ "WCT_CLIP_INC", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY" },
	{ "WCT_CLIP_AP", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING" },
	{ "WCT_CLIP_FMJ", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ" },
	{ "WCT_GRIP", "COMPONENT_AT_AR_AFGRIP_02" },
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_HOLO", "COMPONENT_AT_SIGHTS" },
	{ "WCT_SCOPE_MAC2", "COMPONENT_AT_SCOPE_MACRO_MK2" },
	{ "WCT_SCOPE_MED2", "COMPONENT_AT_SCOPE_MEDIUM_MK2" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP_02" },
	{ "WCT_MUZZ1", "COMPONENT_AT_MUZZLE_01" },
	{ "WCT_MUZZ2", "COMPONENT_AT_MUZZLE_02" },
	{ "WCT_MUZZ3", "COMPONENT_AT_MUZZLE_03" },
	{ "WCT_MUZZ4", "COMPONENT_AT_MUZZLE_04" },
	{ "WCT_MUZZ5", "COMPONENT_AT_MUZZLE_05" },
	{ "WCT_MUZZ6", "COMPONENT_AT_MUZZLE_06" },
	{ "WCT_MUZZ7", "COMPONENT_AT_MUZZLE_07" },
	{ "WCT_BARR", "COMPONENT_AT_AR_BARREL_01" },
	{ "WCT_BARR2", "COMPONENT_AT_AR_BARREL_02" },
	{ "WCT_CAMO_1", "COMPONENT_ASSAULTRIFLE_MK2_CAMO" },
	{ "WCT_CAMO_2", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_02" },
	{ "WCT_CAMO_3", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_03" },
	{ "WCT_CAMO_4", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_04" },
	{ "WCT_CAMO_5", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_05" },
	{ "WCT_CAMO_6", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_06" },
	{ "WCT_CAMO_7", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_07" },
	{ "WCT_CAMO_8", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_08" },
	{ "WCT_CAMO_9", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_09" },
	{ "WCT_CAMO_10", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_10" },
	{ "WCT_CAMO_IND", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01" }
};
const std::vector<std::string> CAPTIONS_ATTACH_ASSAULTRIFLEMK2 = captionsOf(ATTACH_ASSAULTRIFLEMK2_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_ASSAULTRIFLEMK2 = valuesOf(ATTACH_ASSAULTRIFLEMK2_OPTIONS);

const Option<std::string> ATTACH_CARBINERIFLEMK2_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_CARBINERIFLE_MK2_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_CARBINERIFLE_MK2_CLIP_02" },
	{ "WCT_CLIP_TR", "COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER" },
	{ "WCT_CLIP_INC", "COMPONENT_CARBINERIFLE_MK2_CLIP_INCENDIARY" },
	{ "WCT_CLIP_AP", "COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING" },
	{ "WCT_CLIP_FMJ", "COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ" },
	{ "WCT_GRIP", "COMPONENT_AT_AR_AFGRIP_02" },
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_HOLO", "COMPONENT_AT_SIGHTS" },
	{ "WCT_SCOPE_MAC2", "COMPONENT_AT_SCOPE_MACRO_MK2" },
	{ "WCT_SCOPE_MED2", "COMPONENT_AT_SCOPE_MEDIUM_MK2" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP" },
	{ "WCT_MUZZ1", "COMPONENT_AT_MUZZLE_01" },
	{ "WCT_MUZZ2", "COMPONENT_AT_MUZZLE_02" },
	{ "WCT_MUZZ3", "COMPONENT_AT_MUZZLE_03" },
	{ "WCT_MUZZ4", "COMPONENT_AT_MUZZLE_04" },
	{ "WCT_MUZZ5", "COMPONENT_AT_MUZZLE_05" },
	{ "WCT_MUZZ6", "COMPONENT_AT_MUZZLE_06" },
	{ "WCT_MUZZ7", "COMPONENT_AT_MUZZLE_07" },
	{ "WCT_BARR", "COMPONENT_AT_CR_BARREL_01" },
	{ "WCT_BARR2", "COMPONENT_AT_CR_BARREL_02" },
	{ "WCT_CAMO_1", "COMPONENT_CARBINERIFLE_MK2_CAMO" },
	{ "WCT_CAMO_2", "COMPONENT_CARBINERIFLE_MK2_CAMO_02" },
	{ "WCT_CAMO_3", "COMPONENT_CARBINERIFLE_MK2_CAMO_03" },
	{ "WCT_CAMO_4", "COMPONENT_CARBINERIFLE_MK2_CAMO_04" },
	{ "WCT_CAMO_5", "COMPONENT_CARBINERIFLE_MK2_CAMO_05" },
	{ "WCT_CAMO_6", "COMPONENT_CARBINERIFLE_MK2_CAMO_06" },
	{ "WCT_CAMO_7", "COMPONENT_CARBINERIFLE_MK2_CAMO_07" },
	{ "WCT_CAMO_8", "COMPONENT_CARBINERIFLE_MK2_CAMO_08" },
	{ "WCT_CAMO_9", "COMPONENT_CARBINERIFLE_MK2_CAMO_09" },
	{ "WCT_CAMO_10", "COMPONENT_CARBINERIFLE_MK2_CAMO_10" },
	{ "WCT_CAMO_IND", "COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01" }
};
const std::vector<std::string> CAPTIONS_ATTACH_CARBINERIFLEMK2 = captionsOf(ATTACH_CARBINERIFLEMK2_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_CARBINERIFLEMK2 = valuesOf(ATTACH_CARBINERIFLEMK2_OPTIONS);

const Option<std::string> ATTACH_COMBATMGMK2_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_COMBATMG_MK2_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_COMBATMG_MK2_CLIP_02" },
	{ "WCT_CLIP_TR", "COMPONENT_COMBATMG_MK2_CLIP_TRACER" },
	{ "WCT_CLIP_INC", "COMPONENT_COMBATMG_MK2_CLIP_INCENDIARY" },
	{ "WCT_CLIP_AP", "COMPONENT_COMBATMG_MK2_CLIP_ARMORPIERCING" },
	{ "WCT_CLIP_FMJ", "COMPONENT_COMBATMG_MK2_CLIP_FMJ" },
	{ "WCT_GRIP", "COMPONENT_AT_AR_AFGRIP_02" },
	{ "WCT_HOLO", "COMPONENT_AT_SIGHTS" },
	{ "WCT_SCOPE_SML2", "COMPONENT_AT_SCOPE_SMALL_MK2" },
	{ "WCT_SCOPE_MED2", "COMPONENT_AT_SCOPE_MEDIUM_MK2" },
	{ "WCT_MUZZ1", "COMPONENT_AT_MUZZLE_01" },
	{ "WCT_MUZZ2", "COMPONENT_AT_MUZZLE_02" },
	{ "WCT_MUZZ3", "COMPONENT_AT_MUZZLE_03" },
	{ "WCT_MUZZ4", "COMPONENT_AT_MUZZLE_04" },
	{ "WCT_MUZZ5", "COMPONENT_AT_MUZZLE_05" },
	{ "WCT_MUZZ6", "COMPONENT_AT_MUZZLE_06" },
	{ "WCT_MUZZ7", "COMPONENT_AT_MUZZLE_07" },
	{ "WCT_BARR", "COMPONENT_AT_MG_BARREL_01" },
	{ "WCT_BARR2", "COMPONENT_AT_MG_BARREL_02" },
	{ "WCT_CAMO_1", "COMPONENT_COMBATMG_MK2_CAMO" },
	{ "WCT_CAMO_2", "COMPONENT_COMBATMG_MK2_CAMO_02" },
	{ "WCT_CAMO_3", "COMPONENT_COMBATMG_MK2_CAMO_03" },
	{ "WCT_CAMO_4", "COMPONENT_COMBATMG_MK2_CAMO_04" },
	{ "WCT_CAMO_5", "COMPONENT_COMBATMG_MK2_CAMO_05" },
	{ "WCT_CAMO_6", "COMPONENT_COMBATMG_MK2_CAMO_06" },
	{ "WCT_CAMO_7", "COMPONENT_COMBATMG_MK2_CAMO_07" },
	{ "WCT_CAMO_8", "COMPONENT_COMBATMG_MK2_CAMO_08" },
	{ "WCT_CAMO_9", "COMPONENT_COMBATMG_MK2_CAMO_09" },
	{ "WCT_CAMO_10", "COMPONENT_COMBATMG_MK2_CAMO_10" },
	{ "WCT_CAMO_IND", "COMPONENT_COMBATMG_MK2_CAMO_IND_01" }
};
const std::vector<std::string> CAPTIONS_ATTACH_COMBATMGMK2 = captionsOf(ATTACH_COMBATMGMK2_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_COMBATMGMK2 = valuesOf(ATTACH_COMBATMGMK2_OPTIONS);

const Option<std::string> ATTACH_HEAVYSNIPERMK2_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_HEAVYSNIPER_MK2_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_HEAVYSNIPER_MK2_CLIP_02" },
	{ "WCT_CLIP_INC", "COMPONENT_HEAVYSNIPER_MK2_CLIP_INCENDIARY" },
	{ "WCT_CLIP_AP", "COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING" },
	{ "WCT_CLIP_FMJ", "COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ" },
	{ "WCT_CLIP_EX", "COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE" },
	{ "WCT_SCOPE_LRG2", "COMPONENT_AT_SCOPE_LARGE_MK2" },
	{ "WCT_SCOPE_MAX", "COMPONENT_AT_SCOPE_MAX" },
	{ "WCT_SCOPE_NV", "COMPONENT_AT_SCOPE_NV" },
	{ "WCT_SCOPE_TH", "COMPONENT_AT_SCOPE_THERMAL" },
	{ "WCT_SUPP", "COMPONENT_AT_SR_SUPP_03" },
	{ "WCT_MUZZ8", "COMPONENT_AT_MUZZLE_08" },
	{ "WCT_MUZZ9", "COMPONENT_AT_MUZZLE_09" },
	{ "WCT_BARR", "COMPONENT_AT_SR_BARREL_01" },
	{ "WCT_BARR2", "COMPONENT_AT_SR_BARREL_02" },
	{ "WCT_CAMO_1", "COMPONENT_HEAVYSNIPER_MK2_CAMO" },
	{ "WCT_CAMO_2", "COMPONENT_HEAVYSNIPER_MK2_CAMO_02" },
	{ "WCT_CAMO_3", "COMPONENT_HEAVYSNIPER_MK2_CAMO_03" },
	{ "WCT_CAMO_4", "COMPONENT_HEAVYSNIPER_MK2_CAMO_04" },
	{ "WCT_CAMO_5", "COMPONENT_HEAVYSNIPER_MK2_CAMO_05" },
	{ "WCT_CAMO_6", "COMPONENT_HEAVYSNIPER_MK2_CAMO_06" },
	{ "WCT_CAMO_7", "COMPONENT_HEAVYSNIPER_MK2_CAMO_07" },
	{ "WCT_CAMO_8", "COMPONENT_HEAVYSNIPER_MK2_CAMO_08" },
	{ "WCT_CAMO_9", "COMPONENT_HEAVYSNIPER_MK2_CAMO_09" },
	{ "WCT_CAMO_10", "COMPONENT_HEAVYSNIPER_MK2_CAMO_10" },
	{ "WCT_CAMO_IND", "COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01" }
};
const std::vector<std::string> CAPTIONS_ATTACH_HEAVYSNIPERMK2 = captionsOf(ATTACH_HEAVYSNIPERMK2_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_HEAVYSNIPERMK2 = valuesOf(ATTACH_HEAVYSNIPERMK2_OPTIONS);

/*Doomsday Heist*/
const Option<std::string> ATTACH_SNSPISTOLMK2_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_SNSPISTOL_MK2_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_SNSPISTOL_MK2_CLIP_02" },
	{ "WCT_CLIP_TR", "COMPONENT_SNSPISTOL_MK2_CLIP_TRACER" },
	{ "WCT_CLIP_INC", "COMPONENT_SNSPISTOL_MK2_CLIP_INCENDIARY" },
	{ "WCT_CLIP_HP", "COMPONENT_SNSPISTOL_MK2_CLIP_HOLLOWPOINT" },
	{ "WCT_CLIP_FMJ", "COMPONENT_SNSPISTOL_MK2_CLIP_FMJ" },
	{ "WCT_FLASH", "COMPONENT_AT_PI_FLSH_03" },
	{ "WCT_SCOPE_PI", "COMPONENT_AT_PI_RAIL_02" },
	{ "WCT_SUPP", "COMPONENT_AT_PI_SUPP_02" },
	{ "WCT_COMP", "COMPONENT_AT_PI_COMP_02" },
	{ "WCT_CAMO_1", "COMPONENT_SNSPISTOL_MK2_CAMO" },
	{ "WCT_CAMO_2", "COMPONENT_SNSPISTOL_MK2_CAMO_02" },
	{ "WCT_CAMO_3", "COMPONENT_SNSPISTOL_MK2_CAMO_03" },
	{ "WCT_CAMO_4", "COMPONENT_SNSPISTOL_MK2_CAMO_04" },
	{ "WCT_CAMO_5", "COMPONENT_SNSPISTOL_MK2_CAMO_05" },
	{ "WCT_CAMO_6", "COMPONENT_SNSPISTOL_MK2_CAMO_06" },
	{ "WCT_CAMO_7", "COMPONENT_SNSPISTOL_MK2_CAMO_07" },
	{ "WCT_CAMO_8", "COMPONENT_SNSPISTOL_MK2_CAMO_08" },
	{ "WCT_CAMO_9", "COMPONENT_SNSPISTOL_MK2_CAMO_09" },
	{ "WCT_CAMO_10", "COMPONENT_SNSPISTOL_MK2_CAMO_10" },
	{ "WCT_CAMO_IND", "COMPONENT_SNSPISTOL_MK2_CAMO_IND_01" },
	{ "WCT_CAMO_1", "COMPONENT_SNSPISTOL_MK2_CAMO_SLIDE" },
	{ "WCT_CAMO_2", "COMPONENT_SNSPISTOL_MK2_CAMO_02_SLIDE" },
	{ "WCT_CAMO_3", "COMPONENT_SNSPISTOL_MK2_CAMO_03_SLIDE" },
	{ "WCT_CAMO_4", "COMPONENT_SNSPISTOL_MK2_CAMO_04_SLIDE" },
	{ "WCT_CAMO_5", "COMPONENT_SNSPISTOL_MK2_CAMO_05_SLIDE" },
	{ "WCT_CAMO_6", "COMPONENT_SNSPISTOL_MK2_CAMO_06_SLIDE" },
	{ "WCT_CAMO_7", "COMPONENT_SNSPISTOL_MK2_CAMO_07_SLIDE" },
	{ "WCT_CAMO_8", "COMPONENT_SNSPISTOL_MK2_CAMO_08_SLIDE" },
	{ "WCT_CAMO_9", "COMPONENT_SNSPISTOL_MK2_CAMO_09_SLIDE" },
	{ "WCT_CAMO_10", "COMPONENT_SNSPISTOL_MK2_CAMO_10_SLIDE" },
	{ "WCT_CAMO_IND", "COMPONENT_SNSPISTOL_MK2_CAMO_IND_01_SLIDE" }
};
const std::vector<std::string> CAPTIONS_ATTACH_SNSPISTOLMK2 = captionsOf(ATTACH_SNSPISTOLMK2_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_SNSPISTOLMK2 = valuesOf(ATTACH_SNSPISTOLMK2_OPTIONS);

const Option<std::string> ATTACH_REVOLVERMK2_OPTIONS[] = {
	{ "WCT_CLIP1_RV", "COMPONENT_REVOLVER_MK2_CLIP_01" },
	{ "WCT_CLIP_TR", "COMPONENT_REVOLVER_MK2_CLIP_TRACER" },
	{ "WCT_CLIP_INC", "COMPONENT_REVOLVER_MK2_CLIP_INCENDIARY" },
	{ "WCT_CLIP_HP", "COMPONENT_REVOLVER_MK2_CLIP_HOLLOWPOINT" },
	{ "WCT_CLIP_FMJ", "COMPONENT_REVOLVER_MK2_CLIP_FMJ" },
	{ "WCT_HOLO", "COMPONENT_AT_SIGHTS" },
	{ "WCT_SCOPE_MAC2", "COMPONENT_AT_SCOPE_MACRO_MK2" },
	{ "WCT_FLASH", "COMPONENT_AT_PI_FLSH" },
	{ "WCT_COMP", "COMPONENT_AT_PI_COMP_03" },
	{ "WCT_CAMO_1", "COMPONENT_REVOLVER_MK2_CAMO" },
	{ "WCT_CAMO_2", "COMPONENT_REVOLVER_MK2_CAMO_02" },
	{ "WCT_CAMO_3", "COMPONENT_REVOLVER_MK2_CAMO_03" },
	{ "WCT_CAMO_4", "COMPONENT_REVOLVER_MK2_CAMO_04" },
	{ "WCT_CAMO_5", "COMPONENT_REVOLVER_MK2_CAMO_05" },
	{ "WCT_CAMO_6", "COMPONENT_REVOLVER_MK2_CAMO_06" },
	{ "WCT_CAMO_7", "COMPONENT_REVOLVER_MK2_CAMO_07" },
	{ "WCT_CAMO_8", "COMPONENT_REVOLVER_MK2_CAMO_08" },
	{ "WCT_CAMO_9", "COMPONENT_REVOLVER_MK2_CAMO_09" },
	{ "WCT_CAMO_10", "COMPONENT_REVOLVER_MK2_CAMO_10" },
	{ "WCT_CAMO_IND", "COMPONENT_REVOLVER_MK2_CAMO_IND_01" }
};
const std::vector<std::string> CAPTIONS_ATTACH_REVOLVERMK2 = captionsOf(ATTACH_REVOLVERMK2_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_REVOLVERMK2 = valuesOf(ATTACH_REVOLVERMK2_OPTIONS);

const Option<std::string> ATTACH_SPECIALCARBINEMK2_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_SPECIALCARBINE_MK2_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_SPECIALCARBINE_MK2_CLIP_02" },
	{ "WCT_CLIP_TR", "COMPONENT_SPECIALCARBINE_MK2_CLIP_TRACER" },
	{ "WCT_CLIP_INC", "COMPONENT_SPECIALCARBINE_MK2_CLIP_INCENDIARY" },
	{ "WCT_CLIP_AP", "COMPONENT_SPECIALCARBINE_MK2_CLIP_ARMORPIERCING" },
	{ "WCT_CLIP_FMJ", "COMPONENT_SPECIALCARBINE_MK2_CLIP_FMJ" },
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_HOLO", "COMPONENT_AT_SIGHTS" },
	{ "WCT_SCOPE_MAC2", "COMPONENT_AT_SCOPE_MACRO_MK2" },
	{ "WCT_SCOPE_MED2", "COMPONENT_AT_SCOPE_MEDIUM_MK2" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP_02" },
	{ "WCT_MUZZ1", "COMPONENT_AT_MUZZLE_01" },
	{ "WCT_MUZZ2", "COMPONENT_AT_MUZZLE_02" },
	{ "WCT_MUZZ3", "COMPONENT_AT_MUZZLE_03" },
	{ "WCT_MUZZ4", "COMPONENT_AT_MUZZLE_04" },
	{ "WCT_MUZZ5", "COMPONENT_AT_MUZZLE_05" },
	{ "WCT_MUZZ6", "COMPONENT_AT_MUZZLE_06" },
	{ "WCT_MUZZ7", "COMPONENT_AT_MUZZLE_07" },
	{ "WCT_GRIP", "COMPONENT_AT_AR_AFGRIP_02" },
	{ "WCT_BARR", "COMPONENT_AT_SC_BARREL_01" },
	{ "WCT_BARR2", "COMPONENT_AT_SC_BARREL_02" },
	{ "WCT_CAMO_1", "COMPONENT_SPECIALCARBINE_MK2_CAMO" },
	{ "WCT_CAMO_2", "COMPONENT_SPECIALCARBINE_MK2_CAMO_02" },
	{ "WCT_CAMO_3", "COMPONENT_SPECIALCARBINE_MK2_CAMO_03" },
	{ "WCT_CAMO_4", "COMPONENT_SPECIALCARBINE_MK2_CAMO_04" },
	{ "WCT_CAMO_5", "COMPONENT_SPECIALCARBINE_MK2_CAMO_05" },
	{ "WCT_CAMO_6", "COMPONENT_SPECIALCARBINE_MK2_CAMO_06" },
	{ "WCT_CAMO_7", "COMPONENT_SPECIALCARBINE_MK2_CAMO_07" },
	{ "WCT_CAMO_8", "COMPONENT_SPECIALCARBINE_MK2_CAMO_08" },
	{ "WCT_CAMO_9", "COMPONENT_SPECIALCARBINE_MK2_CAMO_09" },
	{ "WCT_CAMO_10", "COMPONENT_SPECIALCARBINE_MK2_CAMO_10" },
	{ "WCT_CAMO_IND", "COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_01" }
};
const std::vector<std::string> CAPTIONS_ATTACH_SPECIALCARBINEMK2 = captionsOf(ATTACH_SPECIALCARBINEMK2_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_SPECIALCARBINEMK2 = valuesOf(ATTACH_SPECIALCARBINEMK2_OPTIONS);

const Option<std::string> ATTACH_BULLPUPMK2_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_02" },
	{ "WCT_CLIP_TR", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_TRACER" },
	{ "WCT_CLIP_INC", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_INCENDIARY" },
	{ "WCT_CLIP_AP", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_ARMORPIERCING" },
	{ "WCT_CLIP_FMJ", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_FMJ" },
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_HOLO", "COMPONENT_AT_SIGHTS" },
	{ "WCT_SCOPE_MAC2", "COMPONENT_AT_SCOPE_MACRO_02_MK2" },
	{ "WCT_SCOPE_SML2", "COMPONENT_AT_SCOPE_SMALL_MK2" },
	{ "WCT_BARR", "COMPONENT_AT_BP_BARREL_01" },
	{ "WCT_BARR2", "COMPONENT_AT_BP_BARREL_02" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP" },
	{ "WCT_MUZZ1", "COMPONENT_AT_MUZZLE_01" },
	{ "WCT_MUZZ2", "COMPONENT_AT_MUZZLE_02" },
	{ "WCT_MUZZ3", "COMPONENT_AT_MUZZLE_03" },
	{ "WCT_MUZZ4", "COMPONENT_AT_MUZZLE_04" },
	{ "WCT_MUZZ5", "COMPONENT_AT_MUZZLE_05" },
	{ "WCT_MUZZ6", "COMPONENT_AT_MUZZLE_06" },
	{ "WCT_MUZZ7", "COMPONENT_AT_MUZZLE_07" },
	{ "WCT_GRIP", "COMPONENT_AT_AR_AFGRIP_02" },
	{ "WCT_CAMO_1", "COMPONENT_BULLPUPRIFLE_MK2_CAMO" },
	{ "WCT_CAMO_2", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_02" },
	{ "WCT_CAMO_3", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_03" },
	{ "WCT_CAMO_4", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_04" },
	{ "WCT_CAMO_5", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_05" },
	{ "WCT_CAMO_6", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_06" },
	{ "WCT_CAMO_7", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_07" },
	{ "WCT_CAMO_8", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_08" },
	{ "WCT_CAMO_9", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_09" },
	{ "WCT_CAMO_10", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_10" },
	{ "WCT_CAMO_IND", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_01" }
};
const std::vector<std::string> CAPTIONS_ATTACH_BULLPUPMK2 = captionsOf(ATTACH_BULLPUPMK2_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_BULLPUPMK2 = valuesOf(ATTACH_BULLPUPMK2_OPTIONS);

const Option<std::string> ATTACH_PUMPSHOTGUNMK2_OPTIONS[] = {
	{ "WCT_SHELL", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_01" },
	{ "WCT_SHELL_INC", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_INCENDIARY" },
	{ "WCT_SHELL_AP", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_ARMORPIERCING" },
	{ "WCT_SHELL_HP", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_HOLLOWPOINT" },
	{ "WCT_SHELL_EX", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_EXPLOSIVE" },
	{ "WCT_HOLO", "COMPONENT_AT_SIGHTS" },
	{ "WCT_SCOPE_MAC2", "COMPONENT_AT_SCOPE_MACRO_MK2" },
	{ "WCT_SCOPE_SML2", "COMPONENT_AT_SCOPE_SMALL_MK2" },
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_SUPP", "COMPONENT_AT_SR_SUPP_03" },
	{ "WCT_MUZZ", "COMPONENT_AT_MUZZLE_08" },
	{ "WCT_CAMO_1", "COMPONENT_PUMPSHOTGUN_MK2_CAMO" },
	{ "WCT_CAMO_2", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_02" },
	{ "WCT_CAMO_3", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_03" },
	{ "WCT_CAMO_4", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_04" },
	{ "WCT_CAMO_5", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_05" },
	{ "WCT_CAMO_6", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_06" },
	{ "WCT_CAMO_7", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_07" },
	{ "WCT_CAMO_8", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_08" },
	{ "WCT_CAMO_9", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_09" },
	{ "WCT_CAMO_10", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_10" },
	{ "WCT_CAMO_IND", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_IND_01" }
};
const std::vector<std::string> CAPTIONS_ATTACH_PUMPSHOTGUNMK2 = captionsOf(ATTACH_PUMPSHOTGUNMK2_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_PUMPSHOTGUNMK2 = valuesOf(ATTACH_PUMPSHOTGUNMK2_OPTIONS);

const Option<std::string> ATTACH_MARKSMANRIFLEMK2_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_02" },
	{ "WCT_CLIP_TR", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_TRACER" },
	{ "WCT_CLIP_INC", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_INCENDIARY" },
	{ "WCT_CLIP_AP", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_ARMORPIERCING" },
	{ "WCT_CLIP_FMJ", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_FMJ" },
	{ "WCT_HOLO", "COMPONENT_AT_SIGHTS" },
	{ "WCT_SCOPE_MED2", "COMPONENT_AT_SCOPE_MEDIUM_MK2" },
	{ "WCT_SCOPE_LRG2", "COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM_MK2" },
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP" },
	{ "WCT_MUZZ1", "COMPONENT_AT_MUZZLE_01" },
	{ "WCT_MUZZ2", "COMPONENT_AT_MUZZLE_02" },
	{ "WCT_MUZZ3", "COMPONENT_AT_MUZZLE_03" },
	{ "WCT_MUZZ4", "COMPONENT_AT_MUZZLE_04" },
	{ "WCT_MUZZ5", "COMPONENT_AT_MUZZLE_05" },
	{ "WCT_MUZZ6", "COMPONENT_AT_MUZZLE_06" },
	{ "WCT_MUZZ7", "COMPONENT_AT_MUZZLE_07" },
	{ "WCT_BARR", "COMPONENT_AT_MRFL_BARREL_01" },
	{ "WCT_BARR2", "COMPONENT_AT_MRFL_BARREL_02" },
	{ "WCT_GRIP", "COMPONENT_AT_AR_AFGRIP_02" },
	{ "WCT_CAMO_1", "COMPONENT_MARKSMANRIFLE_MK2_CAMO" },
	{ "WCT_CAMO_2", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_02" },
	{ "WCT_CAMO_3", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_03" },
	{ "WCT_CAMO_4", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_04" },
	{ "WCT_CAMO_5", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_05" },
	{ "WCT_CAMO_6", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_06" },
	{ "WCT_CAMO_7", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_07" },
	{ "WCT_CAMO_8", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_08" },
	{ "WCT_CAMO_9", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_09" },
	{ "WCT_CAMO_10", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_10" },
	{ "WCT_CAMO_IND", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_IND_01" }
};
const std::vector<std::string> CAPTIONS_ATTACH_MARKSMANRIFLEMK2 = captionsOf(ATTACH_MARKSMANRIFLEMK2_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_MARKSMANRIFLEMK2 = valuesOf(ATTACH_MARKSMANRIFLEMK2_OPTIONS);

const Option<std::string> ATTACH_CERAMIC_PISTOL_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_CERAMICPISTOL_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_CERAMICPISTOL_CLIP_02" },
	{ "WCT_SUPP", "COMPONENT_CERAMICPISTOL_SUPP" }
};
const std::vector<std::string> CAPTIONS_ATTACH_CERAMIC_PISTOL = captionsOf(ATTACH_CERAMIC_PISTOL_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_CERAMIC_PISTOL = valuesOf(ATTACH_CERAMIC_PISTOL_OPTIONS);

//Ray Pistol
const Option<std::string> ATTACH_RAY_PISTOL_OPTIONS[] = {
	{ "WCT_VAR_RAY18", "COMPONENT_RAYPISTOL_VARMOD_XMAS18" }
};
const std::vector<std::string> CAPTIONS_ATTACH_RAY_PISTOL = captionsOf(ATTACH_RAY_PISTOL_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_RAY_PISTOL = valuesOf(ATTACH_RAY_PISTOL_OPTIONS);

//Cayo Perico Heist
const Option<std::string> ATTACH_MILITARYRIFLE_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_MILITARYRIFLE_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_MILITARYRIFLE_CLIP_02" },
	{ "WCT_MRFL_SIGHT", "COMPONENT_MILITARYRIFLE_SIGHT_01" },
	{ "WCT_SCOPE_SML", "COMPONENT_AT_SCOPE_SMALL" },
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP" }
};
const std::vector<std::string> CAPTIONS_ATTACH_MILITARYRIFLE = captionsOf(ATTACH_MILITARYRIFLE_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_MILITARYRIFLE = valuesOf(ATTACH_MILITARYRIFLE_OPTIONS);

const Option<std::string> ATTACH_COMBATSHOTGUN_OPTIONS[] = {
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP" }
};
const std::vector<std::string> CAPTIONS_ATTACH_COMBATSHOTGUN = captionsOf(ATTACH_COMBATSHOTGUN_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_COMBATSHOTGUN = valuesOf(ATTACH_COMBATSHOTGUN_OPTIONS);

//Agency DLC
const Option<std::string> ATTACH_TACTICALRIFLE_OPTIONS[] = {
	{ "WCT_FLASH", "COMPONENT_AT_AR_FLSH_REH" },
	{ "WCT_CLIP2", "COMPONENT_TACTICALRIFLE_CLIP_02" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP_02" },
	{ "WCT_GRIP", "COMPONENT_AT_AR_AFGRIP" }
};
const std::vector<std::string> CAPTIONS_ATTACH_TACTICALRIFLE = captionsOf(ATTACH_TACTICALRIFLE_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_TACTICALRIFLE = valuesOf(ATTACH_TACTICALRIFLE_OPTIONS);

//Xmas 2022 DLC
const Option<std::string> ATTACH_PISTOLXM3_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_PISTOLXM3_CLIP_01" },
	{ "WCT_SUPP", "COMPONENT_PISTOLXM3_SUPP" }
};
const std::vector<std::string> CAPTIONS_ATTACH_PISTOLXM3 = captionsOf(ATTACH_PISTOLXM3_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_PISTOLXM3 = valuesOf(ATTACH_PISTOLXM3_OPTIONS);

//Xmas 2023 DLC
const Option<std::string> ATTACH_BATTLERIFLE_OPTIONS[] = {
	{ "WCT_CLIP1", "COMPONENT_BATTLERIFLE_CLIP_01" },
	{ "WCT_CLIP2", "COMPONENT_BATTLERIFLE_CLIP_02" },
	{ "WCT_SUPP", "COMPONENT_AT_AR_SUPP" }
};
const std::vector<std::string> CAPTIONS_ATTACH_BATTLERIFLE = captionsOf(ATTACH_BATTLERIFLE_OPTIONS);
const std::vector<std::string> VALUES_ATTACH_BATTLERIFLE = valuesOf(ATTACH_BATTLERIFLE_OPTIONS);

//Tintable weapons list
const std::vector<std::string> WEAPONTYPES_TINT{ "WEAPON_PISTOL", "WEAPON_COMBATPISTOL", "WEAPON_APPISTOL", "WEAPON_PISTOL50", "WEAPON_SNSPISTOL", "WEAPON_HEAVYPISTOL", "WEAPON_VINTAGEPISTOL", "WEAPON_STUNGUN", "WEAPON_FLAREGUN", "WEAPON_MARKSMANPISTOL", "WEAPON_MICROSMG", "WEAPON_SMG", "WEAPON_ASSAULTSMG", "WEAPON_MG", "WEAPON_COMBATMG", "WEAPON_GUSENBERG", "WEAPON_ASSAULTRIFLE", "WEAPON_CARBINERIFLE", "WEAPON_ADVANCEDRIFLE", "WEAPON_SPECIALCARBINE", "WEAPON_BULLPUPRIFLE", "WEAPON_PUMPSHOTGUN", "WEAPON_SAWNOFFSHOTGUN", "WEAPON_BULLPUPSHOTGUN", "WEAPON_ASSAULTSHOTGUN", "WEAPON_MUSKET", "WEAPON_HEAVYSHOTGUN", "WEAPON_SNIPERRIFLE", "WEAPON_HEAVYSNIPER", "WEAPON_MARKSMANRIFLE", "WEAPON_GRENADELAUNCHER", "WEAPON_RPG", "WEAPON_MINIGUN", "WEAPON_FIREWORK", "WEAPON_RAILGUN", "WEAPON_HOMINGLAUNCHER", "WEAPON_COMBATPDW", "WEAPON_MACHINEPISTOL", "WEAPON_DBSHOTGUN", "WEAPON_COMPACTRIFLE", "WEAPON_AUTOSHOTGUN", "WEAPON_COMPACTLAUNCHER", "WEAPON_MINISMG", "WEAPON_PISTOL_MK2", "WEAPON_SMG_MK2", "WEAPON_ASSAULTRIFLE_MK2", "WEAPON_CARBINERIFLE_MK2", "WEAPON_COMBATMG_MK2", "WEAPON_HEAVYSNIPER_MK2", /*"WEAPON_SNSPISTOL_MK2", "WEAPON_REVOLVER_MK2", "WEAPON_SPECIALCARBINE_MK2", "WEAPON_BULLPUPRIFLE_MK2", "WEAPON_PUMPSHOTGUN_MK2", "WEAPON_MARKSMANRIFLE_MK2", WEAPON_DOUBLEACTION*/ "WEAPON_RAYPISTOL", "WEAPON_RAYCARBINE", "WEAPON_RAYMINIGUN", "WEAPON_TACTICALRIFLE", "WEAPON_PRECISIONRIFLE", "WEAPON_TECPISTOL", "WEAPON_BATTLERIFLE"};

//Moddable weapons list
const std::vector<std::string> WEAPONTYPES_MOD{ "WEAPON_PISTOL", "WEAPON_HEAVYPISTOL", "WEAPON_COMBATPISTOL", "WEAPON_APPISTOL", "WEAPON_PISTOL50", "WEAPON_MICROSMG", "WEAPON_SMG", "WEAPON_ASSAULTSMG", "WEAPON_ASSAULTRIFLE", "WEAPON_CARBINERIFLE", "WEAPON_ADVANCEDRIFLE", "WEAPON_MG", "WEAPON_COMBATMG", "WEAPON_SAWNOFFSHOTGUN", "WEAPON_PUMPSHOTGUN", "WEAPON_ASSAULTSHOTGUN", "WEAPON_BULLPUPSHOTGUN", "WEAPON_SNIPERRIFLE", "WEAPON_HEAVYSNIPER", "WEAPON_GRENADELAUNCHER", "WEAPON_BULLPUPRIFLE", "WEAPON_GUSENBERG", "WEAPON_HEAVYSHOTGUN", "WEAPON_MARKSMANRIFLE", "WEAPON_SNSPISTOL", "WEAPON_SPECIALCARBINE", "WEAPON_VINTAGEPISTOL", "WEAPON_COMBATPDW", "WEAPON_MACHINEPISTOL", "WEAPON_SWITCHBLADE", "WEAPON_REVOLVER", "WEAPON_COMPACTRIFLE", "WEAPON_MINISMG", "WEAPON_PISTOL_MK2", "WEAPON_SMG_MK2", "WEAPON_ASSAULTRIFLE_MK2", "WEAPON_CARBINERIFLE_MK2", "WEAPON_COMBATMG_MK2", "WEAPON_HEAVYSNIPER_MK2", "WEAPON_SNSPISTOL_MK2", "WEAPON_REVOLVER_MK2", "WEAPON_SPECIALCARBINE_MK2", "WEAPON_BULLPUPRIFLE_MK2", "WEAPON_PUMPSHOTGUN_MK2", "WEAPON_MARKSMANRIFLE_MK2", "WEAPON_CERAMICPISTOL", "WEAPON_MILITARYRIFLE", "WEAPON_COMBATSHOTGUN", "WEAPON_HEAVYRIFLE", "WEAPON_TACTICALRIFLE", "WEAPON_PISTOLXM3", "WEAPON_TECPISTOL", "WEAPON_BATTLERIFLE"};

const std::vector<std::string> VOV_WEAPONMOD_CAPTIONS[] = { CAPTIONS_ATTACH_PISTOL, CAPTIONS_ATTACH_HEAVYPISTOL, CAPTIONS_ATTACH_COMBATPISTOL, CAPTIONS_ATTACH_APPISTOL, CAPTIONS_ATTACH_PISTOL50, CAPTIONS_ATTACH_MICROSMG, CAPTIONS_ATTACH_SMG, CAPTIONS_ATTACH_ASSAULTSMG, CAPTIONS_ATTACH_ASSAULTRIFLE, CAPTIONS_ATTACH_CARBINERIFLE, CAPTIONS_ATTACH_ADVANCEDRIFLE, CAPTIONS_ATTACH_MG, CAPTIONS_ATTACH_COMBATMG, CAPTIONS_ATTACH_SAWNOFF, CAPTIONS_ATTACH_PUMPSHOTGUN, CAPTIONS_ATTACH_ASSAULTSHOTGUN, CAPTIONS_ATTACH_BULLPUPSHOTGUN, CAPTIONS_ATTACH_SNIPERRIFLE, CAPTIONS_ATTACH_HEAVYSNIPER, CAPTIONS_ATTACH_GRENADELAUNCHER, CAPTIONS_ATTACH_BULLPUPRIFLE, CAPTIONS_ATTACH_GUSENBERG, CAPTIONS_ATTACH_HEAVYSHOTGUN, CAPTIONS_ATTACH_MARKSMANRIFLE, CAPTIONS_ATTACH_SNSPISTOL, CAPTIONS_ATTACH_SPECIALCARBINE, CAPTIONS_ATTACH_VINTAGEPISTOL, CAPTIONS_ATTACH_COMBATPDW, CAPTIONS_ATTACH_MACHINEPISTOL, CAPTIONS_ATTACH_SWITCHBLADE, CAPTIONS_ATTACH_REVOLVER, CAPTIONS_ATTACH_COMPACTRIFLE, CAPTIONS_ATTACH_MINISMG, CAPTIONS_ATTACH_PISTOLMK2, CAPTIONS_ATTACH_SMGMK2, CAPTIONS_ATTACH_ASSAULTRIFLEMK2, CAPTIONS_ATTACH_CARBINERIFLEMK2, CAPTIONS_ATTACH_COMBATMGMK2, CAPTIONS_ATTACH_HEAVYSNIPERMK2, CAPTIONS_ATTACH_SNSPISTOLMK2, CAPTIONS_ATTACH_REVOLVERMK2, CAPTIONS_ATTACH_SPECIALCARBINEMK2, CAPTIONS_ATTACH_BULLPUPMK2, CAPTIONS_ATTACH_PUMPSHOTGUNMK2, CAPTIONS_ATTACH_MARKSMANRIFLEMK2, /*CAPTIONS_ATTACH_RAY_PISTOL,*/ CAPTIONS_ATTACH_CERAMIC_PISTOL, CAPTIONS_ATTACH_MILITARYRIFLE, CAPTIONS_ATTACH_COMBATSHOTGUN, CAPTIONS_ATTACH_HEAVYRIFLE, CAPTIONS_ATTACH_TACTICALRIFLE, CAPTIONS_ATTACH_PISTOLXM3, CAPTIONS_ATTACH_WEAPON_TECPISTOL, CAPTIONS_ATTACH_BATTLERIFLE };
const std::vector<std::string> VOV_WEAPONMOD_VALUES[] = { VALUES_ATTACH_PISTOL, VALUES_ATTACH_HEAVYPISTOL, VALUES_ATTACH_COMBATPISTOL, VALUES_ATTACH_APPISTOL, VALUES_ATTACH_PISTOL50, VALUES_ATTACH_MICROSMG, VALUES_ATTACH_SMG, VALUES_ATTACH_ASSAULTSMG, VALUES_ATTACH_ASSAULTRIFLE, VALUES_ATTACH_CARBINERIFLE, VALUES_ATTACH_ADVANCEDRIFLE, VALUES_ATTACH_MG, VALUES_ATTACH_COMBATMG, VALUES_ATTACH_SAWNOFF, VALUES_ATTACH_PUMPSHOTGUN, VALUES_ATTACH_ASSAULTSHOTGUN, VALUES_ATTACH_BULLPUPSHOTGUN, VALUES_ATTACH_SNIPERRIFLE, VALUES_ATTACH_HEAVYSNIPER, VALUES_ATTACH_GRENADELAUNCHER, VALUES_ATTACH_BULLPUPRIFLE, VALUES_ATTACH_GUSENBERG, VALUES_ATTACH_HEAVYSHOTGUN, VALUES_ATTACH_MARKSMANRIFLE, VALUES_ATTACH_SNSPISTOL, VALUES_ATTACH_SPECIALCARBINE, VALUES_ATTACH_VINTAGEPISTOL, VALUES_ATTACH_COMBATPDW, VALUES_ATTACH_MACHINEPISTOL, VALUES_ATTACH_SWITCHBLADE, VALUES_ATTACH_REVOLVER, VALUES_ATTACH_COMPACTRIFLE, VALUES_ATTACH_MINISMG, VALUES_ATTACH_PISTOLMK2, VALUES_ATTACH_SMGMK2, VALUES_ATTACH_ASSAULTRIFLEMK2, VALUES_ATTACH_CARBINERIFLEMK2, VALUES_ATTACH_COMBATMGMK2, VALUES_ATTACH_HEAVYSNIPERMK2, VALUES_ATTACH_SNSPISTOLMK2, VALUES_ATTACH_REVOLVERMK2, VALUES_ATTACH_SPECIALCARBINEMK2, VALUES_ATTACH_BULLPUPMK2, VALUES_ATTACH_PUMPSHOTGUNMK2, VALUES_ATTACH_MARKSMANRIFLEMK2, /*VALUES_ATTACH_RAY_PISTOL,*/ VALUES_ATTACH_CERAMIC_PISTOL, VALUES_ATTACH_MILITARYRIFLE, VALUES_ATTACH_COMBATSHOTGUN, VALUES_ATTACH_HEAVYRIFLE, VALUES_ATTACH_TACTICALRIFLE, VALUES_ATTACH_PISTOLXM3, VALUES_ATTACH_WEAPON_TECPISTOL, VALUES_ATTACH_BATTLERIFLE };

//MK2 weapons 
const std::vector<char*> MK2_WEAPONS{ "WEAPON_PISTOL_MK2", "WEAPON_SNSPISTOL_MK2", "WEAPON_REVOLVER_MK2", "WEAPON_SMG_MK2", "WEAPON_COMBATMG_MK2", "WEAPON_ASSAULTRIFLE_MK2", "WEAPON_BULLPUPRIFLE_MK2", "WEAPON_CARBINERIFLE_MK2", "WEAPON_SPECIALCARBINE_MK2", "WEAPON_PUMPSHOTGUN_MK2", "WEAPON_HEAVYSNIPER_MK2", "WEAPON_MARKSMANRIFLE_MK2" };
const std::vector<char*> MK2_WEAPONS_LIVERY_COMP{ "COMPONENT_PISTOL_MK2_CAMO", "COMPONENT_SNSPISTOL_MK2_CAMO", "COMPONENT_REVOLVER_MK2_CAMO", "COMPONENT_SMG_MK2_CAMO", "COMPONENT_COMBATMG_MK2_CAMO", "COMPONENT_ASSAULTRIFLE_MK2_CAMO", "COMPONENT_BULLPUPRIFLE_MK2_CAMO", "COMPONENT_CARBINERIFLE_MK2_CAMO", "COMPONENT_SPECIALCARBINE_MK2_CAMO", "COMPONENT_PUMPSHOTGUN_MK2_CAMO", "COMPONENT_HEAVYSNIPER_MK2_CAMO", "COMPONENT_MARKSMANRIFLE_MK2_CAMO" };

//Weapon damage modifier list
constexpr Option<float> WEAP_DMG_OPTIONS[] = {
	{ "1.0x", 1.0f }, { "1.5x", 1.5f }, { "2.0x", 2.0f }, { "3.0x", 3.0f }, { "5.0x", 5.0f },
	{ "10.0x", 10.0f }, { "50.0x", 50.0f }, { "100.0x", 100.0f }, { "1000.0x", 1000.0f }
};
const std::vector<std::string> WEAP_DMG_CAPTIONS = captionsOf(WEAP_DMG_OPTIONS);
const std::vector<float> WEAP_DMG_FLOAT_VEC = valuesOf(WEAP_DMG_OPTIONS);
const float* const WEAP_DMG_FLOAT = WEAP_DMG_FLOAT_VEC.data();

const int PARACHUTE_ID = 0xFBAB5776;

const int TOTAL_WEAPONS_COUNT = 100;
const int MAX_MOD_SLOTS = 15; 

extern bool featureNightVision;
extern bool featureThermalVision;
extern int activeLineIndexPowerPunchWeapons;
constexpr Option<int> POWERPUNCH_OPTIONS[] = {
	{ "1", 1 }, { "3", 3 }, { "5", 5 }, { "10", 10 }, { "50", 50 }, { "Manual", 55 }
};
const std::vector<std::string> WEAPONS_POWERPUNCH_CAPTIONS = captionsOf(POWERPUNCH_OPTIONS);
const std::vector<int> WEAPONS_POWERPUNCH_VALUES_VEC = valuesOf(POWERPUNCH_OPTIONS);
const int* const WEAPONS_POWERPUNCH_VALUES = WEAPONS_POWERPUNCH_VALUES_VEC.data();
extern int PowerPunchIndex;
extern bool featurePunchFists;
extern bool featurePunchMeleeWeapons;
extern bool featurePunchFireWeapons;
extern bool featurePowerPunch;
extern std::string lastPowerWeapon;

extern int tick_allw;

bool process_weapon_menu();

bool process_weaponlist_menu();

void reset_weapon_globals();

void update_weapon_features(BOOL bPlayerExists, Player player);

void onchange_cop_armed_index(int value, SelectFromListMenuItem* source);

void onchange_chance_police_calling_index(int value, SelectFromListMenuItem* source);

void onchange_chance_attacking_you_index(int value, SelectFromListMenuItem* source);

void onchange_power_punch_index(int value, SelectFromListMenuItem* source);

void onchange_weapons_firemode_modifier(int value, SelectFromListMenuItem* source);

void onchange_weapons_rapidfire_modifier(int value, SelectFromListMenuItem* source);

void onchange_weap_strobe_index(int value, SelectFromListMenuItem* source);

void onchange_weap_flashdist_index(int value, SelectFromListMenuItem* source);

void onchange_sniper_vision_modifier(int value, SelectFromListMenuItem* source);

void onchange_vehicle_weapon_modifier(int value, SelectFromListMenuItem* source);

void onchange_weapon_no_reticle_modifier(int value, SelectFromListMenuItem* source);

void onchange_weapon_load_saved_modifier(int value, SelectFromListMenuItem* source);

void onchange_cop_alarm_index(int value, SelectFromListMenuItem* source);

void add_weapon_feature_enablements2(std::vector<StringPairSettingDBRow>* results);

void save_player_weapons(Ped playerPed);

void give_all_weapons_hotkey();

void sniper_vision_toggle();

void restore_player_weapons(Ped playerPed);

bool is_weapon_equipped(std::vector<int> extras);

bool process_weapon_save_slot_menu(int slot);

void set_weapon_equipped(bool equipped, std::vector<int> extras);

bool is_weaponmod_equipped(std::vector<int> extras);

void set_weaponmod_equipped(bool equipped, std::vector<int> extras);

void give_weapon_clip(MenuItem<int> choice);

void fill_weapon_ammo(MenuItem<int> choice);

void onconfirm_open_tint_menu(MenuItem<int> choice);

Vector3 DirectionOffsetFromCam(float distance);

void VectorToFloat(Vector3 unk, float *Out);

Vector3 add(Vector3* vectorA, Vector3* vectorB);

//Weapon mod menu
bool onconfirm_weapon_mod_menu_tint(MenuItem<int> choice);

void add_weapon_feature_enablements(std::vector<FeatureEnabledLocalDefinition>* results);

bool weapon_reequip_interrupt();

void onhighlight_weapon_mod_menu_tint_colour(MenuItem<int> choice);

bool onconfirm_weapon_mod_menu_tint_colour(MenuItem<int> choice);

void onconfirm_open_tint_menu_colour(MenuItem<int> choice);

// weapon damage modifier
void onchange_weap_dmg_modifier(int value, SelectFromListMenuItem* source);

void add_weapons_generic_settings(std::vector<StringPairSettingDBRow>* results);

void handle_generic_settings_weapons(std::vector<StringPairSettingDBRow>* settings);

void fire_mode_hotkey();

void add_all_weapons_attachments(Ped choice);

extern Ped equip_ped;